USE COMMERCIAL

DECLARE @CODE_AGENCE INT = 2,
		@CODE_0 INT = 0,
		@DATE_OBJECTIF NVARCHAR(10) = '20180901'

SET @CODE_0 = CAST(CONCAT('990000', @CODE_AGENCE) AS INT)

BEGIN
	SET NOCOUNT ON;
	BEGIN TRY
		BEGIN TRANSACTION
	
		-------- TABLE T_AGENCE ----------
		UPDATE 
			COMMERCIAL.dbo.T_AGENCE 
		SET 
			COD_STD = CONCAT(@CODE_AGENCE, '000001'), 
			COD_LONG = CONCAT(@CODE_AGENCE, '00000001')
		WHERE 
			CODE_AGCE = @CODE_AGENCE

		-------- TABLE T_ZONE ----------
 
		INSERT INTO COMMERCIAL.dbo.T_ZONE 
		(
			CODE_ZONE, 
			NOM_ZONE, 
			CODE_AGCE, 
			CODE_SUPERVISEUR, 
			RESP_VENTE
		)
		SELECT 
			z.CODE_ZONE, 
			z.NOM_ZONE, 
			z.CODE_AGCE, 
			(CASE WHEN z.CODE_SUPERVISEUR = 0 THEN @CODE_0 ELSE z.CODE_SUPERVISEUR END) AS CODE_SUPERVISEUR,
			RESP_VENTE
		FROM 
			AGENCE_TAROUDANT.dbo.T_ZONE z
			INNER JOIN AGENCE_TAROUDANT.dbo.T_AGENCE a ON a.CODE_AGCE = z.CODE_AGCE
		--WHERE 
		--	z.CODE_AGCE = @CODE_AGENCE

		-------- TABLE T_BLOC ----------
 
		INSERT INTO COMMERCIAL.dbo.T_BLOC 
		(
			CODE_BLOC, 
			NOM_BLOC, 
			CODE_ZONE, 
			RANG
		)
		SELECT 
			b.CODE_BLOC, 
			b.NOM_BLOC, 
			b.CODE_ZONE, 
			b.RANG
		FROM 
			AGENCE_TAROUDANT.dbo.T_BLOC b
			INNER JOIN AGENCE_TAROUDANT.dbo.T_ZONE z ON z.CODE_ZONE = b.CODE_ZONE
			INNER JOIN AGENCE_TAROUDANT.dbo.T_AGENCE a ON a.CODE_AGCE = z.CODE_AGCE
		--WHERE 
		--	z.CODE_AGCE = @CODE_AGENCE

		-------- TABLE T_SECTEUR ----------
 
		INSERT INTO COMMERCIAL.dbo.T_SECTEUR 
		(
			CODE_SECTEUR, 
			NOM_SECTEUR, 
			CODE_BLOC, 
			RANG, 
			ACTIF, 
			CAT_SECTEUR, 
			PREVENTE, 
			DERNIER_MAJ, 
			CODE_AGCE
		)
		SELECT 
			(CASE WHEN s.CODE_SECTEUR = 0 THEN @CODE_0 ELSE s.CODE_SECTEUR END) AS CODE_SECTEUR,
			s.NOM_SECTEUR,
			s.CODE_BLOC,
			s.RANG,
			s.ACTIF,
			s.CAT_SECTEUR,
			s.PREVENTE,
			s.DERNIER_MAJ,
			@CODE_AGENCE AS CODE_AGCE 
		FROM 
			AGENCE_TAROUDANT.dbo.T_SECTEUR s
			INNER JOIN AGENCE_TAROUDANT.dbo.T_BLOC b ON b.CODE_BLOC = s.CODE_BLOC
			INNER JOIN AGENCE_TAROUDANT.dbo.T_ZONE z ON z.CODE_ZONE = b.CODE_ZONE
			INNER JOIN AGENCE_TAROUDANT.dbo.T_AGENCE a ON a.CODE_AGCE = z.CODE_AGCE
		--WHERE 
		--	z.CODE_AGCE = @CODE_AGENCE

		-------- TABLE T_SOUS_SECTEUR ----------
 
		INSERT INTO COMMERCIAL.dbo.T_SOUS_SECTEUR 
		(
			CODE_SOUS_SECTEUR, 
			NOM_SOUS_SECTEUR, 
			CODE_SECTEUR, 
			RANG, 
			ACTIF
		)
		SELECT 
			(CASE WHEN ss.CODE_SOUS_SECTEUR = 0 THEN @CODE_0 ELSE ss.CODE_SOUS_SECTEUR END) AS CODE_SOUS_SECTEUR,
			ss.NOM_SOUS_SECTEUR,
			(CASE WHEN ss.CODE_SECTEUR = 0 THEN @CODE_0 ELSE ss.CODE_SECTEUR END) AS CODE_SECTEUR,
			ss.RANG,
			ss.ACTIF 
		FROM 
			AGENCE_TAROUDANT.dbo.T_SOUS_SECTEUR ss
			INNER JOIN AGENCE_TAROUDANT.dbo.T_SECTEUR s ON s.CODE_SECTEUR = ss.CODE_SECTEUR
			INNER JOIN AGENCE_TAROUDANT.dbo.T_BLOC b ON b.CODE_BLOC = s.CODE_BLOC
			INNER JOIN AGENCE_TAROUDANT.dbo.T_ZONE z ON z.CODE_ZONE = b.CODE_ZONE
			INNER JOIN AGENCE_TAROUDANT.dbo.T_AGENCE a ON a.CODE_AGCE = z.CODE_AGCE
		--WHERE 
		--	ss.CODE_SOUS_SECTEUR <> 0


		-------- TABLE T_CAISSE ----------
 

		INSERT INTO COMMERCIAL.dbo.T_CAISSE 
		(
			CODE_CAISSE, 
			NOM_CAISSE, 
			CODE_AGCE, 
			VALEUR_ACT
		)
		SELECT 
			c.CODE_CAISSE,
			c.NOM_CAISSE,
			c.CODE_AGCE,
			c.VALEUR_ACT 
		FROM 
			AGENCE_TAROUDANT.dbo.T_CAISSE c
			INNER JOIN AGENCE_TAROUDANT.dbo.T_AGENCE a ON a.CODE_AGCE = c.CODE_AGCE
		--WHERE 
		--	a.CODE_AGCE = @CODE_AGENCE

		-------- TABLE T_CLIENTS ----------
 
		INSERT INTO COMMERCIAL.dbo.T_CLIENTS 
		(
			CODE_CLIENT, 
			RANG, 
			CAT_CLIENT, 
			NOM_CLIENT, 
			DES_CLIENT, 
			ADRESSE, 
			TELEPHONE, 
			CLASSE, 
			SOUS_SECTEUR, 
			TOURNEE, 
			CLIENT_EN_COMPTE, 
			ACTIF, 
			SOLDE_PRODUITS, 
			SOLDE_CONDITIONNEMENT, 
			SOLDE_C_STD, 
			SOLDE_P_AG, 
			SOLDE_P_UHT, 
			SOLDE_C_AG, 
			SOLDE_C_PR, 
			TYPE_BL, 
			GROUP_CLIENT, 
			AUT_CHEQUE, 
			TYPE_PRESENTOIRE, 
			REMISE_LAIT, 
			CODE_AGCE
		)
		SELECT 
			(CASE WHEN c.CODE_CLIENT = 0 THEN @CODE_0 ELSE c.CODE_CLIENT END) AS CODE_CLIENT,
			c.RANG, 
			c.CAT_CLIENT, 
			c.NOM_CLIENT, 
			c.DES_CLIENT, 
			c.ADRESSE, 
			c.TELEPHONE, 
			c.CLASSE,  
			(CASE WHEN c.SOUS_SECTEUR = 0 THEN @CODE_0 ELSE c.SOUS_SECTEUR END) AS SOUS_SECTEUR,
			(CASE WHEN c.TOURNEE = 0 THEN @CODE_0 ELSE c.TOURNEE END) AS TOURNEE,
			c.CLIENT_EN_COMPTE, 
			c.ACTIF, 
			c.SOLDE_PRODUITS, 
			c.SOLDE_CONDITIONNEMENT, 
			c.SOLDE_C_STD, 
			c.SOLDE_P_AG, 
			c.SOLDE_P_UHT, 
			c.SOLDE_C_AG, 
			c.SOLDE_C_PR, 
			c.TYPE_BL, 
			c.GROUP_CLIENT, 
			c.AUT_CHEQUE, 
			c.TYPE_PRESENTOIRE, 
			c.REMISE_LAIT, 
			@CODE_AGENCE AS CODE_AGCE 
		FROM 
			AGENCE_TAROUDANT.dbo.T_CLIENTS c
		WHERE c.CODE_CLIENT NOT IN (SELECT CODE_CLIENT FROM COMMERCIAL.dbo.T_CLIENTS) AND c.ACTIF = 1
		--INNER JOIN AGENCE_TAROUDANT.dbo.T_SOUS_SECTEUR ss ON ss.CODE_SOUS_SECTEUR = c.SOUS_SECTEUR
		--INNER JOIN AGENCE_TAROUDANT.dbo.T_SECTEUR s ON s.CODE_SECTEUR = ss.CODE_SECTEUR
		--INNER JOIN AGENCE_TAROUDANT.dbo.T_BLOC b ON b.CODE_BLOC = s.CODE_BLOC
		--INNER JOIN AGENCE_TAROUDANT.dbo.T_ZONE z ON z.CODE_ZONE = b.CODE_ZONE
		--INNER JOIN AGENCE_TAROUDANT.dbo.T_AGENCE a ON a.CODE_AGCE = z.CODE_AGCE
		--INNER JOIN AGENCE_TAROUDANT.dbo.T_CAT_CLIENTS cc ON cc.CODE_CAT_CLIENT = c.CAT_CLIENT
		--INNER JOIN AGENCE_TAROUDANT.dbo.T_GROUP_CLIENTS gp ON gp.ID_GP_CLIENT = c.GROUP_CLIENT
		--INNER JOIN AGENCE_TAROUDANT.dbo.T_CLASSE_CLIENTS clc ON clc.CODE_CLASSE = c.CLASSE


		-------- TABLE T_OBJECTIFS ----------
 
		INSERT INTO COMMERCIAL.dbo.T_OBJECTIFS 
		(
			CODE_CLIENT, 
			OBJECTIF, 
			REMISE_OBJECTIF
		)
		SELECT 
			(CASE WHEN o.CODE_CLIENT = 0 THEN @CODE_0 ELSE o.CODE_CLIENT END) AS CODE_CLIENT, 
			o.OBJECTIF, 
			o.REMISE_OBJECTIF
		FROM 
			AGENCE_TAROUDANT.dbo.T_OBJECTIFS o
			INNER JOIN AGENCE_TAROUDANT.dbo.T_CLIENTS c ON c.CODE_CLIENT = o.CODE_CLIENT AND c.ACTIF = 1

		-------- TABLE T_BANQUES ---------- Siege

		INSERT INTO COMMERCIAL.dbo.T_BANQUES 
		(
			NUM_BANQUE, 
			LIBELLE
		)
		SELECT 
			NUM_BANQUE, 
			LIBELLE 
		FROM 
			AGENCE_TAROUDANT.dbo.T_BANQUES
		WHERE NUM_BANQUE NOT IN (SELECT NUM_BANQUE FROM dbo.T_BANQUES)

		-------- TABLE T_COMPTES ----------
 
		INSERT INTO COMMERCIAL.dbo.T_COMPTES 
		(
			CODE_COMPTE,
			NUM_COMPTE, 
			BANQUE
		)
		SELECT 
			(CASE WHEN c.CODE_COMPTE=0 THEN @CODE_0 ELSE c.CODE_COMPTE END) AS CODE_COMPTE,
			c.NUM_COMPTE, 
			c.BANQUE
		FROM 
			AGENCE_TAROUDANT.dbo.T_COMPTES c
			INNER JOIN AGENCE_TAROUDANT.dbo.T_BANQUES b ON b.NUM_BANQUE = c.BANQUE
		WHERE
			CODE_COMPTE NOT IN (SELECT CODE_COMPTE FROM dbo.T_COMPTES)

		-------- TABLE T_ARTICLES ----------

		INSERT INTO COMMERCIAL.dbo.T_ARTICLES 
		(
			CODE_ARTICLE, 
			CODE_BARRE, 
			RANG, 
			LIBELLE_COURT, 
			LIBELLE, 
			ABREVIATION, 
			GP_ARTICLE, 
			CODE_PRODUIT, 
			CODE_AROME, 
			TYPE_CAISSE, 
			TYPE_PALETTE, 
			TVA, 
			AFF_REPARTITION, 
			AFF_COMMANDE, 
			QTE_PACK, 
			QTE_PALETTE, 
			POIDS, 
			CONDITIONNEMENT, 
			ACTIF, 
			ACTIF_GLOBALE, 
			DISPO, 
			TX_COUVERTURE, 
			COMMANDE_MIN
		)
		SELECT 
			a.CODE_ARTICLE, 
			a.CODE_BARRE, 
			a.RANG, 
			a.LIBELLE_COURT, 
			a.LIBELLE, 
			a.ABREVIATION, 
			a.GP_ARTICLE, 
			a.CODE_PRODUIT,
			a.CODE_AROME, 
			NULL, --a.TYPE_CAISSE, 
			NULL, --a.TYPE_PALETTE, 
			a.TVA, 
			a.AFF_REPARTITION, 
			a.AFF_COMMANDE, 
			NULL, --a.QTE_PACK, 
			NULL, --a.QTE_PALETTE, 
			a.POIDS, 
			NULL, --a.CONDITIONNEMENT, 
			NULL, --a.ACTIF, 
			a.ACTIF_GLOBALE, 
			a.DISPO, 
			a.TX_COUVERTURE, 
			a.COMMANDE_MIN 
		FROM 
			AGENCE_TAROUDANT.dbo.T_ARTICLES a
		WHERE 
			a.CODE_ARTICLE NOT IN (SELECT CODE_ARTICLE FROM COMMERCIAL.dbo.T_ARTICLES)

		-------- TABLE T_ARTICLES_AGENCE ----------

		INSERT INTO COMMERCIAL.dbo.T_ARTICLES_AGENCE
		(
		    CODE_ARTICLE,
		    CODE_AGCE,
		    TYPE_CAISSE,
		    TYPE_PALETTE,
		    QTE_PACK,
		    QTE_PALETTE,
		    CONDITIONNEMENT,
		    ACTIF
		)
		SELECT 
			a.CODE_ARTICLE,
		    @CODE_AGENCE,
		    a.TYPE_CAISSE,
		    a.TYPE_PALETTE,
		    a.QTE_PACK,
		    a.QTE_PALETTE,
		    a.CONDITIONNEMENT,
		    a.ACTIF
		FROM 
			AGENCE_TAROUDANT.dbo.T_ARTICLES a

		-------- TABLE T_PRIX_AGENCE ----------
 
		INSERT INTO COMMERCIAL.dbo.T_PRIX_AGENCE 
		(
			CODE_AGCE, 
			CODE_ARTICLE, 
			PRIX_VENTE, 
			TAUX_COMMISSION
		)
		SELECT 
			pa.CODE_AGCE, 
			pa.CODE_ARTICLE, 
			pa.PRIX_VENTE, 
			pa.TAUX_COMMISSION
		FROM 
			AGENCE_TAROUDANT.dbo.T_PRIX_AGENCE pa
			INNER JOIN AGENCE_TAROUDANT.dbo.T_ARTICLES ar ON ar.CODE_ARTICLE = pa.CODE_ARTICLE
		WHERE 
			pa.CODE_AGCE = @CODE_AGENCE
			--INNER JOIN AGENCE_TAROUDANT.dbo.T_AGENCE a ON a.CODE_AGCE = pa.CODE_AGCE

		-------- TABLE T_OPERATEUR ----------
 
		INSERT INTO COMMERCIAL.dbo.T_OPERATEUR 
		(
			CODE_OPERATEUR, 
			CODE_AGCE, 
			MATRICULE, 
			NOM_OPERATEUR, 
			FONCTION, 
			MDP, 
			TITULAIRE, 
			ACTIF, 
			SOLDE_PRODUITS, 
			SOLDE_CONDITIONNEMENT, 
			SOLDE_C_STD, 
			SOLDE_P_AG, 
			SOLDE_P_UHT, 
			SOLDE_C_AG, 
			SOLDE_C_PR, 
			CODE_INTERNE
		)
		SELECT 
			(CASE WHEN o.CODE_OPERATEUR = 0 THEN @CODE_0 ELSE o.CODE_OPERATEUR END) AS CODE_OPERATEUR, 
			o.CODE_AGCE, 
			o.MATRICULE, 
			o.NOM_OPERATEUR, 
			o.FONCTION, 
			o.MDP, 
			o.TITULAIRE, 
			o.ACTIF, 
			o.SOLDE_PRODUITS, 
			o.SOLDE_CONDITIONNEMENT, 
			o.SOLDE_C_STD, 
			o.SOLDE_P_AG, 
			o.SOLDE_P_UHT, 
			o.SOLDE_C_AG, 
			o.SOLDE_C_PR, 
			o.CODE_INTERNE 
		FROM 
			AGENCE_TAROUDANT.dbo.T_OPERATEUR o
		WHERE 
			o.CODE_OPERATEUR NOT IN (SELECT CODE_OPERATEUR FROM COMMERCIAL.dbo.T_OPERATEUR)
		--INNER JOIN AGENCE_TAROUDANT.dbo.T_FONCTION f ON f.CODE_FONCTION = o.FONCTION
		--INNER JOIN AGENCE_TAROUDANT.dbo.T_AGENCE a ON a.CODE_AGCE = o.CODE_AGCE
		--WHERE a.CODE_AGCE=2

		-------- TABLE T_TACHES ----------
 
		INSERT INTO COMMERCIAL.dbo.T_TACHES 
		(
			ID_TACHE, 
			APP, 
			LIBELLE_TACHE,
			RANG
		)
		SELECT 
			t.ID_TACHE,
			t.APP,
			t.LIBELLE_TACHE,
			t.RANG 
		FROM 
			AGENCE_TAROUDANT.dbo.T_TACHES t
		WHERE 
			t.ID_TACHE NOT IN (SELECT ID_TACHE FROM COMMERCIAL.dbo.T_TACHES)

		-------- TABLE T_OPERTEURS_TACHES ----------
 
		INSERT INTO COMMERCIAL.dbo.T_OPERTEURS_TACHES 
		(
			CODE_OPERATEUR, 
			ID_TACHE, 
			ETAT
		)
		SELECT DISTINCT
			(CASE WHEN ot.CODE_OPERATEUR = 0 THEN @CODE_0 ELSE ot.CODE_OPERATEUR END) AS CODE_OPERATEUR, 
			ot.ID_TACHE,
			ot.ETAT 
		FROM 
			AGENCE_TAROUDANT.dbo.T_OPERTEURS_TACHES ot
			INNER JOIN AGENCE_TAROUDANT.dbo.T_OPERATEUR o ON o.CODE_OPERATEUR = ot.CODE_OPERATEUR
			--INNER JOIN AGENCE_TAROUDANT.dbo.T_AGENCE a ON a.CODE_AGCE = o.CODE_AGCE
			INNER JOIN AGENCE_TAROUDANT.dbo.T_TACHES t ON t.ID_TACHE = ot.ID_TACHE
		--WHERE a.CODE_AGCE=2

		-------- TABLE T_APPAREIL ----------
		INSERT INTO COMMERCIAL.dbo.T_APPAREIL 
		( 
			NUMERO_SERIE, 
			NUMERO_SIM, 
			ICCID_SIM, 
			PIN_SIM, 
			PUK_SIM, 
			FORFAIT_SIM, 
			CODE_OPERATEUR, 
			CODE_AGCE, 
			OBSERVATION, 
			LOGIN_RDP, 
			PWD_RDP, 
			DATE_ADD, 
			USER_ACCEPTATION, 
			DATE_ACCEPTATION, 
			USER_ARRET, 
			DATE_ARRET, 
			LAST_CONNECTION
		)
		SELECT  
			ap.NUMERO_SERIE, 
			ap.NUMERO_SIM, 
			ap.ICCID_SIM, 
			ap.PIN_SIM, 
			ap.PUK_SIM, 
			ap.FORFAIT_SIM, 
			(CASE WHEN ap.CODE_OPERATEUR = 0 THEN @CODE_0 ELSE ap.CODE_OPERATEUR END ) AS CODE_OPERATEUR, 
			@CODE_AGENCE AS CODE_AGENCE, 
			ap.OBSERVATION, 
			ap.LOGIN_RDP, 
			ap.PWD_RDP, 
			ap.DATE_ADD, 
			ap.USER_ACCEPTATION, 
			ap.DATE_ACCEPTATION, 
			ap.USER_ARRET, 
			ap.DATE_ARRET, 
			ap.LAST_CONNECTION
		FROM 
			AGENCE_TAROUDANT.dbo.T_APPAREIL ap
		--INNER JOIN AGENCE_TAROUDANT.dbo.T_AGENCE a ON a.CODE_AGCE = ap.CODE_AGCE
		--INNER JOIN AGENCE_TAROUDANT.dbo.T_OPERATEUR o ON o.CODE_OPERATEUR = ap.CODE_OPERATEUR
		--WHERE 
		--	ap.CODE_AGCE = @CODE_AGENCE
		WHERE
			ap.NUMERO_SERIE NOT IN (SELECT NUMERO_SERIE FROM T_APPAREIL)

		-------- TABLE T_VEHICULE ----------
 
		INSERT INTO COMMERCIAL.dbo.T_VEHICULE 
		(
			MATRICULE, 
			PROPRIETAIRE, 
			CAPACITE, 
			TONNAGE, 
			ACTIF, 
			LIEU
		)
		SELECT 
			MATRICULE,
			PROPRIETAIRE,
			CAPACITE,
			TONNAGE,
			ACTIF,
			LIEU 
		FROM 
			AGENCE_TAROUDANT.dbo.T_VEHICULE
		WHERE 
			MATRICULE NOT IN (SELECT MATRICULE FROM COMMERCIAL.dbo.T_VEHICULE)

		-------- TABLE T_PARAMETRES ----------
 
		INSERT INTO COMMERCIAL.dbo.T_PARAMETRES 
		( 
			ID_LIGNE,
			LIBELLE, 
			VALEUR, 
			CODE_AGCE
		)
		SELECT 
			p.ID_LIGNE,
			p.NOM_PARAMETRE,
			p.VALEUR,
			@CODE_AGENCE AS CODE_AGCE 
		FROM 
			AGENCE_TAROUDANT.dbo.T_PARAMETRES p

		-------- TABLE T_MAGASINS ----------
 
		INSERT INTO COMMERCIAL.dbo.T_MAGASINS 
		(
			CODE_MAGASIN, 
			NOM_MAGASIN, 
			CODE_AGCE
		)
		SELECT
			m.CODE_MAGASIN, 
			m.NOM_MAGASIN, 
			m.CODE_AGCE
		FROM 
			AGENCE_TAROUDANT.dbo.T_MAGASINS m
		--INNER JOIN AGENCE_TAROUDANT.dbo.T_AGENCE a ON a.CODE_AGCE = m.CODE_AGCE
		--WHERE a.CODE_AGCE=2

		-------- TABLE T_TYPE_PRODUIT_MAG ----------
 
		INSERT INTO COMMERCIAL.dbo.T_TYPE_PRODUIT_MAG 
		(
			CODE_MAGASIN, 
			PRODUIT
		)
		SELECT 
			pm.CODE_MAGASIN, 
			pm.PRODUIT
		FROM 
			AGENCE_TAROUDANT.dbo.T_TYPE_PRODUIT_MAG pm
			INNER JOIN AGENCE_TAROUDANT.dbo.T_MAGASINS m ON m.CODE_MAGASIN = pm.CODE_MAGASIN
		--WHERE m.CODE_AGCE=2

		-------- TABLE T_TOURNEES ----------
 
		INSERT INTO COMMERCIAL.dbo.T_TOURNEES 
		(
			CODE_TOURNEE, 
			NOM_TOURNEE, 
			CODE_SECTEUR, 
			ROTATION, 
			NBRE_JOURS, 
			ACTIF
		)
		SELECT 
			(CASE WHEN t.CODE_TOURNEE = 0 THEN @CODE_0 ELSE t.CODE_TOURNEE END)  AS CODE_TOURNEE, 
			t.NOM_TOURNEE,
			(CASE WHEN t.CODE_SECTEUR = 0 THEN @CODE_0 ELSE t.CODE_SECTEUR END)  AS CODE_SECTEUR, 
			t.ROTATION,
			t.NBRE_JOURS,
			t.ACTIF 
		FROM 
			AGENCE_TAROUDANT.dbo.T_TOURNEES t
			INNER JOIN AGENCE_TAROUDANT.dbo.T_SECTEUR s ON s.CODE_SECTEUR = t.CODE_SECTEUR
		--WHERE s.CODE_AGCE=2

		-------- TABLE T_ITINERAIRES ----------
 
		INSERT INTO COMMERCIAL.dbo.T_ITINERAIRES 
		(
			CODE_TOURNEE, 
			CODE_CLIENT, 
			RANG, 
			RANG_PREVENTE
		)
		SELECT 
			(CASE WHEN i.CODE_TOURNEE = 0 THEN @CODE_0 ELSE i.CODE_TOURNEE END) AS CODE_TOURNEE,
			(CASE WHEN i.CODE_CLIENT = 0 THEN @CODE_0 ELSE i.CODE_CLIENT END) AS CODE_CLIENT, 
			i.RANG,
			i.RANG_PREVENTE 
		FROM 
			AGENCE_TAROUDANT.dbo.T_ITINERAIRES i
			INNER JOIN AGENCE_TAROUDANT.dbo.T_TOURNEES t ON t.CODE_TOURNEE = i.CODE_TOURNEE
			INNER JOIN AGENCE_TAROUDANT.dbo.T_SECTEUR s ON s.CODE_SECTEUR = t.CODE_SECTEUR
			INNER JOIN AGENCE_TAROUDANT.dbo.T_CLIENTS c ON c.CODE_CLIENT = i.CODE_CLIENT AND c.ACTIF = 1
		--WHERE s.CODE_AGCE=2 AND c.CODE_AGCE=2

		-------- TABLE T_JOURNEE ----------
 
		INSERT INTO COMMERCIAL.dbo.T_JOURNEE
		(
			DATE_JOURNEE,
			CODE_AGCE,
			STOCK,
			SOLDE_EMB,
			CLOTURE,
			JOURNEE_TEMP,
			SOLDE_CAISSE,
			AS_C_STD,
			AS_P_AG,
			AS_P_UHT,
			AS_C_AG,
			AS_C_PR,
			NS_C_STD,
			NS_P_AG,
			NS_P_UHT,
			NS_C_AG,
			NS_C_PR,
			SOLDE_CAISSERIE,
			TEMP_MIN,
			TEMP_MAX,
			PLUV,
			COMMENTAIRE,
			AS_P_EURO,
			AS_CS_BLC,
			NS_PAL_EURO,
			NS_CS_BLC,
			AS_CS1,
			AS_CS2,
			NV_CS1,
			NV_CS2
		)
		SELECT 
			j.DATE_JOURNEE,
			j.CODE_AGCE,
			j.STOCK,
			j.SOLDE_EMB,
			j.CLOTURE,
			j.JOURNEE_TEMP,
			j.SOLDE_CAISSE,
			j.AS_C_STD,
			j.AS_P_AG,
			j.AS_P_UHT,
			j.AS_C_AG,
			j.AS_C_PR,
			j.NS_C_STD,
			j.NS_P_AG,
			j.NS_P_UHT,
			j.NS_C_AG,
			j.NS_C_PR,
			j.SOLDE_CAISSERIE,
			j.TEMP_MIN,
			j.TEMP_MAX,
			j.PLUV,
			j.COMMENTAIRE,
			j.AS_P_EURO,
			j.AS_CS_BLC,
			j.NS_PAL_EURO,
			j.NS_CS_BLC,
			j.AS_CS1,
			j.AS_CS2,
			j.NV_CS1,
			j.NV_CS2 
		FROM 
			AGENCE_TAROUDANT.dbo.T_JOURNEE j
			--INNER JOIN AGENCE_TAROUDANT.dbo.T_AGENCE a ON a.CODE_AGCE = j.CODE_AGCE
		WHERE 
			j.DATE_JOURNEE >= @DATE_OBJECTIF 
			--AND a.CODE_AGCE = @CODE_AGENCE

		-------- TABLE T_STOCK_INIT ----------
 
		INSERT INTO COMMERCIAL.dbo.T_STOCK_INIT
		(
			DATE_PS,
			CODE_ARTICLE,
			CODE_MAGASIN,
			CATEGORIE,
			QTE_INIT,
			CODE_AGCE
		)
		SELECT 
			s.DATE_PS,
			s.CODE_ARTICLE,
			s.CODE_MAGASIN,
			s.CATEGORIE,
			s.QTE_INIT, 
			@CODE_AGENCE AS CODE_AGCE 
		FROM 
			AGENCE_TAROUDANT.dbo.T_STOCK_INIT s
			INNER JOIN AGENCE_TAROUDANT.dbo.T_MAGASINS m ON m.CODE_MAGASIN = s.CODE_MAGASIN
			--INNER JOIN AGENCE_TAROUDANT.dbo.T_ARTICLES a ON a.CODE_ARTICLE = s.CODE_ARTICLE
		WHERE 
			s.DATE_PS >= @DATE_OBJECTIF
			--AND m.CODE_AGCE = @CODE_AGENCE

		-------- TABLE T_STOCK_INITI_COND ----------
 
		INSERT INTO COMMERCIAL.dbo.T_STOCK_INITI_COND
		(
			DATE_JOURNEE,
			CODE_MAGASIN,
			CODE_CP,
			STOCK_INIT,
			CODE_AGCE
		)
		SELECT 
			s.DATE_JOURNEE,
			s.CODE_MAGASIN,
			s.CODE_CP,
			s.STOCK_INIT,
			@CODE_AGENCE AS CODE_AGCE 
		FROM 
			AGENCE_TAROUDANT.dbo.T_STOCK_INITI_COND s
			INNER JOIN AGENCE_TAROUDANT.dbo.T_MAGASINS m ON m.CODE_MAGASIN = s.CODE_MAGASIN
		WHERE 
			s.DATE_JOURNEE >= @DATE_OBJECTIF
			--AND m.CODE_AGCE=2

		-------- TABLE T_SOLDE_INITIAL ----------
 
		INSERT INTO COMMERCIAL.dbo.T_SOLDE_INITIAL
		(
			DATE_JOURNEE,
			CODE_OPERATEUR,
			SOLDE_PRODUITS,
			SOLDE_CONDITIONNEMENT,
			MT_A_VERSER,
			MT_VERSER,
			MT_CHEQUES,
			TOTAL_VERSER,
			MT_ECART,
			SOLDE_C_STD,
			SOLDE_P_AG,
			SOLDE_P_UHT,
			SOLDE_C_AG,
			SOLDE_C_PR,
			SOLDE_C_BLC,
			SOLDE_P_EURO,
			SOLDE_CS1,
			SOLDE_CS2,
			CODE_AGCE
		)
		SELECT 
			s.DATE_JOURNEE,
			(CASE WHEN s.CODE_OPERATEUR = 0 THEN @CODE_0 ELSE s.CODE_OPERATEUR END) AS CODE_OPERATEUR,
			s.SOLDE_PRODUITS,
			s.SOLDE_CONDITIONNEMENT,
			s.MT_A_VERSER,
			s.MT_VERSER,
			s.MT_CHEQUES,
			s.TOTAL_VERSER,
			s.MT_ECART,
			s.SOLDE_C_STD,
			s.SOLDE_P_AG,
			s.SOLDE_P_UHT,
			s.SOLDE_C_AG,
			s.SOLDE_C_PR,
			s.SOLDE_C_BLC,
			s.SOLDE_P_EURO,
			s.SOLDE_CS1,
			s.SOLDE_CS2, 
			@CODE_AGENCE AS CODE_AGCE 
		FROM 
			AGENCE_TAROUDANT.dbo.T_SOLDE_INITIAL s
			INNER JOIN AGENCE_TAROUDANT.dbo.T_OPERATEUR o ON o.CODE_OPERATEUR = s.CODE_OPERATEUR
		WHERE 
			s.DATE_JOURNEE >= @DATE_OBJECTIF 
			--AND o.CODE_AGCE=2

		-------- TABLE T_SOLDE_INITIAL_CAISSE ----------
 
		INSERT INTO COMMERCIAL.dbo.T_SOLDE_INITIAL_CAISSE
		(
			DATE_JOURNEE,
			CODE_CAISSE,
			SOLDE_INITIAL
		)
		SELECT 
			s.DATE_JOURNEE,
			s.CODE_CAISSE,
			s.SOLDE_INITIAL 
		FROM 
			AGENCE_TAROUDANT.dbo.T_SOLDE_INITIAL_CAISSE s
			INNER JOIN AGENCE_TAROUDANT.dbo.T_CAISSE c ON c.CODE_CAISSE = s.CODE_CAISSE
		WHERE 
			s.DATE_JOURNEE >= @DATE_OBJECTIF 
			--AND c.CODE_AGCE = @CODE_AGENCE

		-------- TABLE T_SOLDE_INITIAL_CLIENT ----------
 
		INSERT INTO COMMERCIAL.dbo.T_SOLDE_INITIAL_CLIENT
		(
			DATE_JOURNEE,
			CODE_CLIENT,
			SOLDE_PRODUITS,
			SOLDE_CONDITIONNEMENT,
			SOLDE_C_STD,
			SOLDE_P_AG,
			SOLDE_P_UHT,
			SOLDE_C_AG,
			SOLDE_C_PR,
			SOLDE_P_EURO,
			SOLDE_C_BLC,
			SOLDE_CS1,
			SOLDE_CS2,
			CODE_AGCE
		)
		SELECT 
			s.DATE_JOURNEE,
			(CASE WHEN s.CODE_CLIENT = 0 THEN @CODE_0 ELSE s.CODE_CLIENT END) AS CODE_CLIENT, 
			s.SOLDE_PRODUITS,
			s.SOLDE_CONDITIONNEMENT,
			s.SOLDE_C_STD,
			s.SOLDE_P_AG,
			s.SOLDE_P_UHT,
			s.SOLDE_C_AG,
			s.SOLDE_C_PR,
			s.SOLDE_P_EURO,
			s.SOLDE_C_BLC,
			s.SOLDE_CS1,
			s.SOLDE_CS2, 
			@CODE_AGENCE AS CODE_AGCE 
		FROM 
			AGENCE_TAROUDANT.dbo.T_SOLDE_INITIAL_CLIENT s
			INNER JOIN AGENCE_TAROUDANT.dbo.T_CLIENTS c ON c.CODE_CLIENT = s.CODE_CLIENT AND c.ACTIF = 1
		WHERE 
			s.DATE_JOURNEE >= @DATE_OBJECTIF
			--AND c.CODE_AGCE = @CODE_AGENCE

		-------- TABLE T_AUTORISATIONS_SOLDE ----------
 
		INSERT INTO COMMERCIAL.dbo.T_AUTORISATIONS_SOLDE
		(
			ID_JUSTIFICATION,
			DATE_OPERATION,
			CREER_PAR,
			ORDRE_PAR,
			MONTANT,
			DATE_ECHU,
			CODE_CLIENT,
			CA_CLIENT,
			VERSION,
			CODE_SECTEUR,
			CODE_OPERATEUR,
			NUM_FACTURE,
			TEl_CLIENT
		)
		SELECT 
			a.ID_JUSTIFICATION,
			a.DATE_OPERATION,
			a.CREER_PAR,
			a.ORDRE_PAR,
			a.MONTANT,
			a.DATE_ECHU,
			(CASE WHEN a.CODE_CLIENT = 0 THEN @CODE_0 ELSE a.CODE_CLIENT END) AS CODE_CLIENT, 
			a.CA_CLIENT,
			a.VERSION,
			(CASE WHEN a.CODE_SECTEUR = 0 THEN @CODE_0 ELSE a.CODE_SECTEUR END)  AS CODE_SECTEUR,
			(CASE WHEN a.CODE_OPERATEUR = 0 THEN @CODE_0 ELSE a.CODE_OPERATEUR END) AS CODE_OPERATEUR, 
			a.NUM_FACTURE,
			a.TEl_CLIENT 
		FROM 
			AGENCE_TAROUDANT.dbo.T_AUTORISATIONS_SOLDE a
			INNER JOIN AGENCE_TAROUDANT.dbo.T_OPERATEUR o ON o.CODE_OPERATEUR = a.CODE_OPERATEUR
		WHERE 
			(a.DATE_OPERATION >= @DATE_OBJECTIF OR a.DATE_ECHU >= @DATE_OBJECTIF) 
			--AND o.CODE_AGCE=2  1 semaine min

		-------- TABLE T_AUTORISATION_SOLDE_CAISSERIE ----------
 
		INSERT INTO COMMERCIAL.dbo.T_AUTORISATION_SOLDE_CAISSERIE
		(
			ID_JUSTIFICATION,
			CODE_OPERATEUR,
			DATE_HEURE,
			DATE_ECHU,
			PAR_ORDRE,
			SAISIE_PAR,
			CS_STD,
			CS_PR,
			CS_AG,
			CS_BLC,
			PAL_AG,
			PAL_UHT,
			PAL_EURO,
			CS1,
			CS2
		)
		SELECT 
			a.ID_JUSTIFICATION,
			(CASE WHEN a.CODE_OPERATEUR = 0 THEN @CODE_0 ELSE a.CODE_OPERATEUR END) AS CODE_OPERATEUR,
			a.DATE_HEURE,
			a.DATE_ECHU,
			a.PAR_ORDRE,
			a.SAISIE_PAR,
			a.CS_STD,
			a.CS_PR,
			a.CS_AG,
			a.CS_BLC,
			a.PAL_AG,
			a.PAL_UHT,
			a.PAL_EURO,
			a.CS1,
			a.CS2 
		FROM 
			AGENCE_TAROUDANT.dbo.T_AUTORISATION_SOLDE_CAISSERIE a
			INNER JOIN AGENCE_TAROUDANT.dbo.T_OPERATEUR o ON o.CODE_OPERATEUR = a.CODE_OPERATEUR	
		WHERE 
			(a.DATE_HEURE >= @DATE_OBJECTIF OR a.DATE_ECHU >= @DATE_OBJECTIF) 
			--AND o.CODE_AGCE=2

		-------- TABLE T_REPARTITION ----------
 
		INSERT INTO COMMERCIAL.dbo.T_REPARTITION
		(
			DATE_REPARTITION,
			CODE_AGENCE,
			LIVRAISONS,
			VALIDATION,
			CODE_OPERATEUR,
			CONTROLEUR_PRODUIT,
			CONTROLEUR_COND
		)
		SELECT 
			r.DATE_REPARTITION,
			r.CODE_AGENCE,
			r.LIVRAISONS,
			r.VALIDATION,
			(CASE WHEN r.CODE_OPERATEUR = 0 THEN @CODE_0 ELSE r.CODE_OPERATEUR END) AS CODE_OPERATEUR,
			r.CONTROLEUR_PRODUIT,
			r.CONTROLEUR_COND 
		FROM 
			AGENCE_TAROUDANT.dbo.T_REPARTITION r
			--INNER JOIN AGENCE_TAROUDANT.dbo.T_AGENCE a ON a.CODE_AGCE = r.CODE_AGENCE
			--INNER JOIN AGENCE_TAROUDANT.dbo.T_OPERATEUR o ON o.CODE_OPERATEUR = r.CODE_OPERATEUR
		WHERE 
			r.DATE_REPARTITION >= @DATE_OBJECTIF
			--AND a.CODE_AGCE = @CODE_AGENCE

		-------- TABLE T_OPERATIONS ----------
 
		INSERT INTO COMMERCIAL.dbo.T_OPERATIONS
		(
			CODE_OPERATION,
			TYPE_OPERATION,
			DATE_OPERATION,
			CODE_CLIENT,
			DATE_HEURE,
			CODE_OPERATEUR,
			COMMENTAIRE,
			NUM_CONVOYAGE,
			MOTIF,
			CODE_AGCE1,
			CODE_AGCE2,
			CODE_MAGASIN1,
			CODE_MAGASIN2,
			TYPE_PRODUIT,
			REF,
			CATEGORIE1,
			CATEGORIE2,
			COMPTE_ECART,
			SOUS_TYPE_OPERATION,
			CODE_AGCE
		)
		SELECT 
			o.CODE_OPERATION,
			o.TYPE_OPERATION,
			o.DATE_OPERATION,
			(CASE WHEN o.CODE_CLIENT = 0 THEN @CODE_0 ELSE o.CODE_CLIENT END) AS CODE_CLIENT, 
			o.DATE_HEURE,
			(CASE WHEN o.CODE_OPERATEUR = 0 THEN @CODE_0 ELSE o.CODE_OPERATEUR END) AS CODE_OPERATEUR, 
			o.COMMENTAIRE,
			o.NUM_CONVOYAGE,
			o.MOTIF,
			o.CODE_AGCE1,
			o.CODE_AGCE2,
			o.CODE_MAGASIN1,
			o.CODE_MAGASIN2,
			o.TYPE_PRODUIT,
			o.REF,
			o.CATEGORIE1,
			o.CATEGORIE2,
			o.COMPTE_ECART,
			o.SOUS_TYPE_OPERATION, 
			@CODE_AGENCE AS CODE_AGCE 
		FROM 
			AGENCE_TAROUDANT.dbo.T_OPERATIONS o
			--INNER JOIN AGENCE_TAROUDANT.dbo.T_OPERATEUR op ON op.CODE_OPERATEUR = o.CODE_OPERATEUR
		WHERE 
			o.DATE_OPERATION >= @DATE_OBJECTIF 
			--AND op.CODE_AGCE=2

		-------- TABLE T_OPERATIONS_CAISSE ----------
 
		INSERT INTO COMMERCIAL.dbo.T_OPERATIONS_CAISSE
		(
			CODE_OPERATION,
			TYPE_OPERATION,
			DATE_OPERATION,
			DATE_VALIDATION,
			LIBELLE,
			NUM_PIECE,
			NATURE,
			BENEFICIAIRE,
			COMPTE_VERSEMENT,
			COMMENTAIRE,
			MONTANT,
			MOTIF_ENVOI,
			CODE_AGCE
		)
		SELECT 
			oc.CODE_OPERATION,
			oc.TYPE_OPERATION,
			oc.DATE_OPERATION,
			oc.DATE_VALIDATION,
			oc.LIBELLE,
			oc.NUM_PIECE,
			oc.NATURE,
			oc.BENEFICIAIRE,
			(CASE WHEN oc.COMPTE_VERSEMENT = 0 THEN @CODE_0 ELSE oc.COMPTE_VERSEMENT END) AS COMPTE_VERSEMENT,
			oc.COMMENTAIRE,
			oc.MONTANT,
			oc.MOTIF_ENVOI, 
			@CODE_AGENCE AS CODE_AGCE 
		FROM 
			AGENCE_TAROUDANT.dbo.T_OPERATIONS_CAISSE oc
			--INNER JOIN AGENCE_TAROUDANT.dbo.T_OPERATIONS o ON o.CODE_OPERATION = oc.CODE_OPERATION
		WHERE 
			(oc.DATE_OPERATION >= @DATE_OBJECTIF 
			OR oc.DATE_VALIDATION >= @DATE_OBJECTIF)
		--WHERE oc.CODE_OPERATION NOT IN (SELECT CODE_OPERATION FROM COMMERCIAL.dbo.T_OPERATIONS_CAISSE)

		-------- TABLE T_MOUVEMENTS_CAISSE ----------
 
		INSERT INTO COMMERCIAL.dbo.T_MOUVEMENTS_CAISSE
		(
			ID_MOUVEMENT,
			CODE_CAISSE,
			TYPE_MVT,
			ORIGINE,
			MONTANT
		)
		SELECT 
			mc.ID_MOUVEMENT,
			mc.CODE_CAISSE,
			mc.TYPE_MVT,
			mc.ORIGINE,
			mc.MONTANT 
		FROM 
			AGENCE_TAROUDANT.dbo.T_MOUVEMENTS_CAISSE mc
			INNER JOIN AGENCE_TAROUDANT.dbo.T_CAISSE c ON c.CODE_CAISSE = mc.CODE_CAISSE
			INNER JOIN AGENCE_TAROUDANT.dbo.T_OPERATIONS_CAISSE oc ON oc.CODE_OPERATION = mc.ORIGINE
		WHERE 
			(oc.DATE_OPERATION >= @DATE_OBJECTIF OR oc.DATE_VALIDATION >= @DATE_OBJECTIF)
		--WHERE (oc.DATE_OPERATION >= '20180916' OR oc.DATE_VALIDATION >= '20180916') --AND c.CODE_AGCE=2

		-------- TABLE T_MOUVEMENTS ----------
 
		INSERT INTO COMMERCIAL.dbo.T_MOUVEMENTS
		(
			ID_MOUVEMENT,
			CODE_MAGASIN,
			DATE_MVT,
			TYPE_MOUVEMENT,
			ORIGINE,
			TYPE_PRODUIT,
			CODE_ARTICLE,
			QTE_THEORIQUE,
			QTE_REEL,
			QTE_ECART,
			QTE_MOUVEMENT,
			QTE_CAISSE,
			QTE_PAL,
			PRIX,
			MONTANT,
			MONTANT_ECART,
			COMPTE_ECART,
			CODE_CLIENT,
			DATE_HEURE_MOUVEMENT,
			CODE_OPERATEUR,
			MOTIF
		)
		SELECT 
			mo.ID_MOUVEMENT,
			mo.CODE_MAGASIN,
			mo.DATE_MVT,
			mo.TYPE_MOUVEMENT,
			mo.ORIGINE,
			mo.TYPE_PRODUIT,
			mo.CODE_ARTICLE,
			mo.QTE_THEORIQUE,
			mo.QTE_REEL,
			mo.QTE_ECART,
			mo.QTE_MOUVEMENT,
			mo.QTE_CAISSE,
			mo.QTE_PAL,
			mo.PRIX,
			mo.MONTANT,
			mo.MONTANT_ECART,
			(CASE WHEN mo.COMPTE_ECART = 0 THEN @CODE_0 ELSE mo.COMPTE_ECART END) AS COMPTE_ECART,
			(CASE WHEN mo.CODE_CLIENT = 0 THEN @CODE_0 ELSE mo.CODE_CLIENT END) AS CODE_CLIENT, 
			mo.DATE_HEURE_MOUVEMENT,
			mo.CODE_OPERATEUR,
			mo.MOTIF 
		FROM 
			AGENCE_TAROUDANT.dbo.T_MOUVEMENTS mo
			INNER JOIN AGENCE_TAROUDANT.dbo.T_OPERATIONS o ON o.CODE_OPERATION = mo.ORIGINE
			--INNER JOIN AGENCE_TAROUDANT.dbo.T_MAGASINS m ON m.CODE_MAGASIN = mo.CODE_MAGASIN
			--INNER JOIN AGENCE_TAROUDANT.dbo.T_OPERATEUR o ON o.CODE_OPERATEUR = mo.CODE_OPERATEUR
		WHERE 
			o.DATE_OPERATION >= @DATE_OBJECTIF
			--WHERE mo.DATE_HEURE_MOUVEMENT >= '20180916' AND m.CODE_AGCE=2

		-------- TABLE T_MOUVEMENTS_CAISSERIE ----------
 
		INSERT INTO COMMERCIAL.dbo.T_MOUVEMENTS_CAISSERIE
		(
			ID_MOUVEMENT,
			CODE_MAGASIN,
			CODE_CP,
			TYPE_MOUVEMENT,
			ORIGINE,
			QTE_THEORIQUE,
			QTE_REEL,
			QTE_ECART,
			QTE_MOUVEMENT,
			PRIX,
			MONTANT_ECART,
			CODE_OPERATEUR,
			COMPTE_ECART
		)
		SELECT DISTINCT 
			mc.ID_MOUVEMENT,
			mc.CODE_MAGASIN,
			mc.CODE_CP,
			mc.TYPE_MOUVEMENT,
			mc.ORIGINE,
			mc.QTE_THEORIQUE,
			mc.QTE_REEL,
			mc.QTE_ECART,
			mc.QTE_MOUVEMENT,
			mc.PRIX,
			mc.MONTANT_ECART,
			(CASE WHEN mc.CODE_OPERATEUR = 0 THEN @CODE_0 ELSE mc.CODE_OPERATEUR END) AS CODE_OPERATEUR, 
			(CASE WHEN mc.COMPTE_ECART = 0 THEN @CODE_0 ELSE mc.COMPTE_ECART END) AS COMPTE_ECART
		FROM 
			AGENCE_TAROUDANT.dbo.T_MOUVEMENTS_CAISSERIE mc
			INNER JOIN AGENCE_TAROUDANT.dbo.T_OPERATIONS o ON o.CODE_OPERATION = mc.ORIGINE
		WHERE 
			o.DATE_OPERATION >= @DATE_OBJECTIF
		--INNER JOIN AGENCE_TAROUDANT.dbo.T_MAGASINS ms ON mc.CODE_MAGASIN = ms.CODE_MAGASIN
		--WHERE ms.CODE_AGCE=2
		--WHERE m.DATE_HEURE_MOUVEMENT >= '20180916' AND ms.CODE_AGCE=2

		-------- TABLE T_ARTICLES_MAGASINS ----------
 
		INSERT INTO COMMERCIAL.dbo.T_ARTICLES_MAGASINS
		(
			CODE_ARTICLE,
			MAGASIN,
			CATEGORIE,
			QTE_STOCK
		)
		SELECT 
			am.CODE_ARTICLE,
			am.MAGASIN,
			am.CATEGORIE,
			am.QTE_STOCK 
		FROM 
			AGENCE_TAROUDANT.dbo.T_ARTICLES_MAGASINS am
			INNER JOIN AGENCE_TAROUDANT.dbo.T_ARTICLES a ON a.CODE_ARTICLE = am.CODE_ARTICLE
			INNER JOIN dbo.T_MAGASINS m ON m.CODE_MAGASIN = am.MAGASIN
		--WHERE m.CODE_AGCE=2

		-------- TABLE T_CHARGEMENT ----------
 
		INSERT INTO COMMERCIAL.dbo.T_CHARGEMENT
		(
			CODE_CHARGEMENT,
			DATE_CHARGEMENT,
			CHARGEMENT_CAC,
			CODE_SECTEUR,
			CODE_AGCE,
			CODE_TOURNEE,
			VEHICULE,
			CODE_VENDEUR,
			CODE_CHAUFFEUR,
			AIDE_VENDEUR1,
			AIDE_VENDEUR2,
			VALID,
			MONTANT_A_VERSER,
			HEURE_SORTIE,
			HEURE_ENTREE,
			KM_PARCOURUS,
			HEURE_ENTREE_EXEMP,
			CODE_PREVENDEUR,
			ID_VEHICULE,
			ID_VEHICULE_PV,
			ID_TRANSPORTEUR
		)
		SELECT 
			CAST(CONCAT(@CODE_AGENCE,c.CODE_CHARGEMENT) AS BIGINT) AS CODE_CHARGEMENT,
			c.DATE_CHARGEMENT,
			c.CHARGEMENT_CAC,
			(CASE WHEN c.CODE_SECTEUR = 0 THEN @CODE_0 ELSE c.CODE_SECTEUR END)  AS CODE_SECTEUR, 
			c.CODE_AGCE,
			(CASE WHEN c.CODE_TOURNEE = 0 THEN @CODE_0 ELSE c.CODE_TOURNEE END) AS CODE_TOURNEE,
			c.VEHICULE,
			(CASE WHEN c.CODE_VENDEUR = 0 THEN @CODE_0 ELSE c.CODE_VENDEUR END)  AS CODE_VENDEUR,
			(CASE WHEN c.CODE_CHAUFFEUR = 0 THEN @CODE_0 ELSE c.CODE_CHAUFFEUR END)  AS CODE_CHAUFFEUR, 
			(CASE WHEN c.AIDE_VENDEUR1 = 0 THEN @CODE_0 ELSE c.AIDE_VENDEUR1 END)  AS AIDE_VENDEUR1, 
			(CASE WHEN c.AIDE_VENDEUR2 = 0 THEN @CODE_0 ELSE c.AIDE_VENDEUR2 END)  AS AIDE_VENDEUR2,  
			c.VALID,
			c.MONTANT_A_VERSER,
			c.HEURE_SORTIE,
			c.HEURE_ENTREE,
			c.KM_PARCOURUS,
			c.HEURE_ENTREE_EXEMP,
			(CASE WHEN c.CODE_PREVENDEUR = 0 THEN @CODE_0 ELSE c.CODE_PREVENDEUR END)  AS CODE_PREVENDEUR, 
			c.ID_VEHICULE,
			c.ID_VEHICULE_PV,
			c.ID_TRANSPORTEUR 
		FROM 
			AGENCE_TAROUDANT.dbo.T_CHARGEMENT c
			INNER JOIN AGENCE_TAROUDANT.dbo.T_SECTEUR s ON s.CODE_SECTEUR = c.CODE_SECTEUR
			--INNER JOIN AGENCE_TAROUDANT.dbo.T_TOURNEES t ON t.CODE_TOURNEE = c.CODE_TOURNEE
		WHERE 
			c.DATE_CHARGEMENT >= @DATE_OBJECTIF

		-------- TABLE T_COND_CHARGEE ----------
 
		INSERT INTO COMMERCIAL.dbo.T_COND_CHARGEE
		(
			CODE_CHARGEMENT,
			CODE_COND,
			CODE_SECTEUR,
			CODE_OPERATEUR,
			DATE_CHARGEMENT,
			QTE_CHARGEE,
			QTE_CHARGEE_VAL,
			QTE_POINTE,
			QTE_CHAR_SUPP,
			QTE_RETOUR,
			ECART,
			VALEUR_ECART,
			CREDIT,
			VALEUR_CREDIT,
			COMPTE_ECART
		)
		SELECT 
			CAST(CONCAT(@CODE_AGENCE,cc.CODE_CHARGEMENT) AS BIGINT) AS CODE_CHARGEMENT,
			cc.CODE_COND,
			(CASE WHEN cc.CODE_SECTEUR = 0 THEN @CODE_0 ELSE cc.CODE_SECTEUR END)  AS CODE_SECTEUR, 
			(CASE WHEN cc.CODE_OPERATEUR = 0 THEN @CODE_0 ELSE cc.CODE_OPERATEUR END)  AS CODE_OPERATEUR, 
			cc.DATE_CHARGEMENT,
			cc.QTE_CHARGEE,
			cc.QTE_CHARGEE_VAL,
			cc.QTE_POINTE,
			cc.QTE_CHAR_SUPP,
			cc.QTE_RETOUR,
			cc.ECART,
			cc.VALEUR_ECART,
			cc.CREDIT,
			cc.VALEUR_CREDIT,
			(CASE WHEN cc.COMPTE_ECART = 0 THEN @CODE_0 ELSE cc.COMPTE_ECART END)  AS COMPTE_ECART
		FROM 
			AGENCE_TAROUDANT.dbo.T_COND_CHARGEE cc
			INNER JOIN AGENCE_TAROUDANT.dbo.T_CHARGEMENT c ON c.CODE_CHARGEMENT = cc.CODE_CHARGEMENT
		WHERE 
			c.DATE_CHARGEMENT >= @DATE_OBJECTIF

		-------- TABLE T_PRODUITS_CHARGEE ----------
 
		INSERT INTO COMMERCIAL.dbo.T_PRODUITS_CHARGEE
		(
			CODE_CHARGEMENT,
			CODE_ARTICLE,
			CODE_SECTEUR,
			CODE_VENDEUR,
			DATE_CHARGEMENT,
			QTE_CHARGEE,
			QTE_CHARGEE_VAL,
			QTE_COND,
			QTE_CHARGEE_POINTE,
			QTE_CHARGEE_SUPP,
			TOTAL_CHARGEE,
			QTE_ECART,
			COMPTE_ECART,
			TOTAL_VENDU,
			MONTANT,
			CREDIT,
			MONTANT_CREDIT,
			TOTAL_GRATUIT,
			TOTAL_DONS,
			TOTAL_ECHANGE,
			TOTAL_REMISE,
			TOTAL_RENDUS_POINTE,
			TOTAL_RENDUS_AG,
			TOTAL_RENDUS_US,
			TOTAL_RENDUS_COM,
			TOTAL_RENDUS_SP,
			TOTAL_INVENDU_POINTE,
			PRIX,
			MONTANT_ECART,
			CMD_U,
			CMD_C,
			PRIX_VNT
		)
		SELECT 
			CAST(CONCAT(@CODE_AGENCE,pc.CODE_CHARGEMENT) AS BIGINT) AS CODE_CHARGEMENT,
			pc.CODE_ARTICLE,
			(CASE WHEN pc.CODE_SECTEUR = 0 THEN @CODE_0 ELSE pc.CODE_SECTEUR END)  AS CODE_SECTEUR, 
			(CASE WHEN pc.CODE_VENDEUR = 0 THEN @CODE_0 ELSE pc.CODE_VENDEUR END)  AS CODE_VENDEUR,
			pc.DATE_CHARGEMENT,
			pc.QTE_CHARGEE,
			pc.QTE_CHARGEE_VAL,
			pc.QTE_COND,
			pc.QTE_CHARGEE_POINTE,
			pc.QTE_CHARGEE_SUPP,
			pc.TOTAL_CHARGEE,
			pc.QTE_ECART,
			(CASE WHEN pc.COMPTE_ECART = 0 THEN @CODE_0 ELSE pc.COMPTE_ECART END)  AS COMPTE_ECART,
			pc.TOTAL_VENDU,
			pc.MONTANT,
			pc.CREDIT,
			pc.MONTANT_CREDIT,
			pc.TOTAL_GRATUIT,
			pc.TOTAL_DONS,
			pc.TOTAL_ECHANGE,
			pc.TOTAL_REMISE,
			pc.TOTAL_RENDUS_POINTE,
			pc.TOTAL_RENDUS_AG,
			pc.TOTAL_RENDUS_US,
			pc.TOTAL_RENDUS_COM,
			pc.TOTAL_RENDUS_SP,
			pc.TOTAL_INVENDU_POINTE,
			pc.PRIX,
			pc.MONTANT_ECART,
			pc.CMD_U,
			pc.CMD_C,
			pc.PRIX_VNT 
		FROM 
			AGENCE_TAROUDANT.dbo.T_PRODUITS_CHARGEE pc
			INNER JOIN AGENCE_TAROUDANT.dbo.T_CHARGEMENT c ON c.CODE_CHARGEMENT = pc.CODE_CHARGEMENT
		WHERE 
			c.DATE_CHARGEMENT >= @DATE_OBJECTIF

		-------- TABLE T_PREPARATION_CHARGEMENTS ----------
 
		INSERT COMMERCIAL.dbo.T_PREPARATION_CHARGEMENTS
		(
			CODE_ARTICLE,
			IMPORTE,
			SORTIE1,
			SORTIE2,
			CHARG_GMS,
			REST_STOCK,
			CODE_AGCE
		)
		SELECT 
			CODE_ARTICLE,
			IMPORTE,
			SORTIE1,
			SORTIE2,
			CHARG_GMS,
			REST_STOCK, 
			@CODE_AGENCE AS CODE_AGCE 
		FROM 
			AGENCE_TAROUDANT.dbo.T_PREPARATION_CHARGEMENTS

		-------- TABLE T_LIVRAISON ----------
 
		INSERT INTO COMMERCIAL.dbo.T_LIVRAISON
		(
			NUM_LIVRAISON,
			DATE_LIVRAISON,
			CODE_CLIENT,
			CODE_SECTEUR,
			TYPE_LIVRAISON,
			CODE_OPERATEUR,
			DATE_HEURE,
			CODE_VENDEUR,
			CHAUFFEUR,
			AIDE_VENDEUR1,
			AIDE_VENDEUR2,
			VEHICULE,
			STATUT,
			LIVRAISON_TOURNEE,
			DATE_VALIDATION,
			TYPE_MVT,
			BENEFICIAIRE,
			ORDONATEUR,
			NUM_COMMANDE,
			SUR_COMMANDE,
			MOTIF_ENVOI,
			OS,
			MOTIF_NON_VALIDATION,
			CODE_AGCE
		)
		SELECT 
			l.NUM_LIVRAISON,
			l.DATE_LIVRAISON,
			(CASE WHEN l.CODE_CLIENT = 0 THEN @CODE_0 ELSE l.CODE_CLIENT END) AS CODE_CLIENT, 
			(CASE WHEN l.CODE_SECTEUR = 0 THEN @CODE_0 ELSE l.CODE_SECTEUR END) AS CODE_SECTEUR, 
			l.TYPE_LIVRAISON,
			(CASE WHEN l.CODE_OPERATEUR = 0 THEN @CODE_0 ELSE l.CODE_OPERATEUR END) AS CODE_OPERATEUR, 
			l.DATE_HEURE,
			(CASE WHEN l.CODE_VENDEUR = 0 THEN @CODE_0 ELSE l.CODE_VENDEUR END) AS CODE_VENDEUR, 
			(CASE WHEN l.CHAUFFEUR = 0 THEN @CODE_0 ELSE l.CHAUFFEUR END) AS CHAUFFEUR, 
			(CASE WHEN l.AIDE_VENDEUR1 = 0 THEN @CODE_0 ELSE l.AIDE_VENDEUR1 END) AS AIDE_VENDEUR1, 
			(CASE WHEN l.AIDE_VENDEUR2 = 0 THEN @CODE_0 ELSE l.AIDE_VENDEUR2 END) AS AIDE_VENDEUR2, 
			l.VEHICULE,
			l.STATUT,
			l.LIVRAISON_TOURNEE,
			l.DATE_VALIDATION,
			l.TYPE_MVT,
			l.BENEFICIAIRE,
			l.ORDONATEUR,
			l.NUM_COMMANDE,
			l.SUR_COMMANDE,
			l.MOTIF_ENVOI,
			l.OS,
			l.MOTIF_NON_VALIDATION, 
			@CODE_AGENCE AS CODE_AGCE 
		FROM 
			AGENCE_TAROUDANT.dbo.T_LIVRAISON l
			--INNER JOIN AGENCE_TAROUDANT.dbo.T_OPERATEUR o ON o.CODE_OPERATEUR = l.CODE_OPERATEUR
		WHERE 
			l.DATE_LIVRAISON >= @DATE_OBJECTIF

		-------- TABLE T_COND_LIVRAISON ----------
 
		INSERT INTO COMMERCIAL.dbo.T_COND_LIVRAISON
		(
			NUM_LIVRAISON,
			CODE_CP,
			CODE_MAGASIN,
			CODE_OPERATEUR,
			CODE_SECTEUR,
			CODE_CLIENT,
			TYPE_CLIENT,
			QTE_IMPORTE,
			QTE_CHARGEE,
			VALEUR_CHARGEE,
			PRIX,
			STATUT,
			DATE_VALIDATION,
			TYPE_MVT
		)
		SELECT 
			cl.NUM_LIVRAISON,
			cl.CODE_CP,
			cl.CODE_MAGASIN,
			(CASE WHEN cl.CODE_OPERATEUR = 0 THEN @CODE_0 ELSE cl.CODE_OPERATEUR END) AS CODE_OPERATEUR, 
			(CASE WHEN cl.CODE_SECTEUR = 0 THEN @CODE_0 ELSE cl.CODE_SECTEUR END) AS CODE_SECTEUR, 
			(CASE WHEN cl.CODE_CLIENT = 0 THEN @CODE_0 ELSE cl.CODE_CLIENT END) AS CODE_CLIENT,
			cl.TYPE_CLIENT,
			cl.QTE_IMPORTE,
			cl.QTE_CHARGEE,
			cl.VALEUR_CHARGEE,
			cl.PRIX,
			cl.STATUT,
			cl.DATE_VALIDATION,
			cl.TYPE_MVT 
		FROM 
			AGENCE_TAROUDANT.dbo.T_COND_LIVRAISON cl
			INNER JOIN AGENCE_TAROUDANT.dbo.T_LIVRAISON l ON l.NUM_LIVRAISON = cl.NUM_LIVRAISON
		WHERE 
			l.DATE_LIVRAISON >= @DATE_OBJECTIF

		-------- TABLE T_PRODUITS_LIVREES ----------
 
		INSERT INTO COMMERCIAL.dbo.T_PRODUITS_LIVREES
		(
			NUM_LIVRAISON,
			CODE_ARTICLE,
			CODE_CLIENT,
			CODE_VENDEUR,
			CODE_MAGASIN,
			CODE_SECTEUR,
			TYPE_CLIENT,
			QTE_COMMANDE,
			QTE_IMPORTE,
			QTE_CHARGEE,
			MONTANT,
			PRIX,
			QTE_CAISSE,
			QTE_PAL,
			STATUT,
			DATE_VALIDATION,
			TYPE_MVT,
			MOTIF_RETOUR
		)
		SELECT 
			pl.NUM_LIVRAISON,
			pl.CODE_ARTICLE,
			(CASE WHEN pl.CODE_CLIENT = 0 THEN @CODE_0 ELSE pl.CODE_CLIENT END) AS CODE_CLIENT,
			(CASE WHEN pl.CODE_VENDEUR = 0 THEN @CODE_0 ELSE pl.CODE_VENDEUR END) AS CODE_VENDEUR,
			pl.CODE_MAGASIN,
			(CASE WHEN pl.CODE_SECTEUR = 0 THEN @CODE_0 ELSE pl.CODE_SECTEUR END) AS CODE_SECTEUR,
			pl.TYPE_CLIENT,
			pl.QTE_COMMANDE,
			pl.QTE_IMPORTE,
			pl.QTE_CHARGEE,
			pl.MONTANT,
			pl.PRIX,
			pl.QTE_CAISSE,
			pl.QTE_PAL,
			pl.STATUT,
			pl.DATE_VALIDATION,
			pl.TYPE_MVT,
			pl.MOTIF_RETOUR 
		FROM 
			AGENCE_TAROUDANT.dbo.T_PRODUITS_LIVREES pl
			INNER JOIN AGENCE_TAROUDANT.dbo.T_LIVRAISON l ON l.NUM_LIVRAISON = pl.NUM_LIVRAISON
		WHERE 
			l.DATE_HEURE >= @DATE_OBJECTIF

		-------- TABLE T_COMMANDES ----------
 
		INSERT INTO COMMERCIAL.dbo.T_COMMANDES
		(
			ID_COMMANDE,
			TYPE_COMMANDE,
			DATE_LIVRAISON,
			CODE_SECTEUR,
			CODE_CLIENT,
			CODE_AGENCE,
			CODE_OPERATEUR,
			DATE_HEURE_SAISIE,
			NUM_COMMANDE,
			DATE_COMMANDE,
			OS,
			ID_OS
		)
		SELECT 
			c.ID_COMMANDE,
			c.TYPE_COMMANDE,
			c.DATE_LIVRAISON,
			(CASE WHEN c.CODE_SECTEUR = 0 THEN @CODE_0 ELSE c.CODE_SECTEUR END) AS CODE_SECTEUR, 
			(CASE WHEN c.CODE_CLIENT = 0 THEN @CODE_0 ELSE c.CODE_CLIENT END) AS CODE_CLIENT,
			@CODE_AGENCE,
			(CASE WHEN c.CODE_OPERATEUR = 0 THEN @CODE_0 ELSE c.CODE_OPERATEUR END) AS CODE_OPERATEUR,
			c.DATE_HEURE_SAISIE,
			c.NUM_COMMANDE,
			c.DATE_COMMANDE,
			c.OS,
			c.ID_OS 
		FROM 
			AGENCE_TAROUDANT.dbo.T_COMMANDES c
			INNER JOIN AGENCE_TAROUDANT.dbo.T_SECTEUR s ON s.CODE_SECTEUR = c.CODE_SECTEUR
			--INNER JOIN AGENCE_TAROUDANT.dbo.T_CLIENTS cl ON cl.CODE_CLIENT = c.CODE_CLIENT
			--INNER JOIN AGENCE_TAROUDANT.dbo.T_AGENCE a ON a.CODE_AGCE = c.CODE_AGENCE
			--INNER JOIN AGENCE_TAROUDANT.dbo.T_OPERATEUR o ON o.CODE_OPERATEUR = c.CODE_OPERATEUR
		WHERE 
			CAST(c.DATE_HEURE_SAISIE AS DATE) >= @DATE_OBJECTIF

		-------- TABLE T_PRODUITS_COMMANDES ----------
 
		INSERT INTO COMMERCIAL.dbo.T_PRODUITS_COMMANDES
		(
			ID_COMMANDE,
			CODE_ARTICLE,
			QTE_U,
			QTE_C,
			QTE_P
		)
		SELECT 
			pc.ID_COMMANDE,
			pc.CODE_ARTICLE,
			pc.QTE_U,
			pc.QTE_C,
			pc.QTE_P
		FROM 
			AGENCE_TAROUDANT.dbo.T_PRODUITS_COMMANDES pc
			INNER JOIN AGENCE_TAROUDANT.dbo.T_COMMANDES c ON c.ID_COMMANDE = pc.ID_COMMANDE
			--INNER JOIN AGENCE_TAROUDANT.dbo.T_ARTICLES a ON a.CODE_ARTICLE = pc.CODE_ARTICLE
		WHERE 
			CAST(c.DATE_HEURE_SAISIE AS DATE) >= @DATE_OBJECTIF

		-------- TABLE T_BORDEREAU_VALEURS ----------
 
		INSERT INTO COMMERCIAL.dbo.T_BORDEREAU_VALEURS
		(
			ID_BORDEREAU,
			CODE_BANQUE,
			VALID,
			DATE_HEURE_SAISIE,
			SAISIE_PAR,
			ACTIF,
			NUM_BORDEAU_BANQUE,
			DATE_SITUATION
		)
		SELECT 
			ID_BORDEREAU,
			CODE_BANQUE,
			VALID,
			DATE_HEURE_SAISIE,
			SAISIE_PAR,
			ACTIF,
			NUM_BORDEAU_BANQUE,
			DATE_SITUATION 
		FROM 
			AGENCE_TAROUDANT.dbo.T_BORDEREAU_VALEURS
		WHERE 
			CAST(DATE_HEURE_SAISIE AS DATE) >= @DATE_OBJECTIF

		-------- TABLE T_DT_BORDEREAU ----------
 
		INSERT INTO COMMERCIAL.dbo.T_DT_BORDEREAU
		(
			ID_BORDEREAU,
			NUM_DECOMPTE
		)
		SELECT  
			dtb.ID_BORDEREAU,
			dtb.NUM_DECOMPTE
		FROM 
			AGENCE_TAROUDANT.dbo.T_DT_BORDEREAU dtb
			INNER JOIN AGENCE_TAROUDANT.dbo.T_BORDEREAU_VALEURS b ON b.ID_BORDEREAU = dtb.ID_BORDEREAU
		WHERE CAST(b.DATE_HEURE_SAISIE AS DATE) >= @DATE_OBJECTIF

		-------- TABLE T_BUDGET_MENSUEL ----------
 
		INSERT INTO COMMERCIAL.dbo.T_BUDGET_MENSUEL
		(
			DATE_BUDGET,
			CODE_ARTICLE,
			QTE,
			CODE_AGCE
		)
		SELECT 
			b.DATE_BUDGET,
			b.CODE_ARTICLE,
			b.QTE, 
			@CODE_AGENCE AS CODE_AGCE 
		FROM 
			AGENCE_TAROUDANT.dbo.T_BUDGET_MENSUEL b
			INNER JOIN AGENCE_TAROUDANT.dbo.T_ARTICLES a ON a.CODE_ARTICLE = b.CODE_ARTICLE
		WHERE 
			b.DATE_BUDGET >= @DATE_OBJECTIF

		-------- TABLE T_RECLAMATIONS_QUALITE ----------
/* 
		INSERT INTO COMMERCIAL.dbo.T_RECLAMATIONS_QUALITE
		(
			ID_RECLAMATION,
			DATE_HEURE,
			EMETTEUR,
			DESCRIPTION,
			CODE_ARTICLE,
			DLC,
			QTE_NC,
			TYPE,
			ORIGINE,
			NBRE_CLIENTS,
			DATE_RECLAMATION,
			CODE_AGCE
		)
		SELECT 
			r.ID_RECLAMATION,
			r.DATE_HEURE,
			r.EMETTEUR,
			r.DESCRIPTION,
			r.CODE_ARTICLE,
			r.DLC,
			r.QTE_NC,
			r.TYPE,
			r.ORIGINE,
			r.NBRE_CLIENTS,
			r.DATE_RECLAMATION,
			2 CODE_AGCE 
		FROM 
			AGENCE_TAROUDANT.dbo.T_RECLAMATIONS_QUALITE r
		WHERE 
			r.DATE_RECLAMATION >= @DATE_OBJECTIF

		-------- TABLE T_DT_RECLAMATION ----------
 
		INSERT INTO COMMERCIAL.dbo.T_DT_RECLAMATION
		(
			ID_RECLAMATION,
			ID_MOTIF
		)
		SELECT 
			dtr.ID_RECLAMATION,
			dtr.ID_MOTIF
		FROM 
			AGENCE_TAROUDANT.dbo.T_DT_RECLAMATION dtr
			INNER JOIN AGENCE_TAROUDANT.dbo.T_RECLAMATIONS_QUALITE r ON r.ID_RECLAMATION = dtr.ID_RECLAMATION
		WHERE r.DATE_RECLAMATION >= @DATE_OBJECTIF
*/
		-------- TABLE T_DECOMPTE ----------
 
		INSERT INTO COMMERCIAL.dbo.T_DECOMPTE
		(
			NUM_DECOMPTE,
			CODE_OPERATEUR,
			DATE_DECOMPTE,
			MODE_PAIEMENT,
			CODE_CAISSE,
			MONTANT,
			DATE_HEURE_VERS,
			CODE_CLIENT,
			CODE_BANQUE,
			REFERENCE,
			REGLEMENT,
			DATE_VALIDATION,
			CODE_AGCE
		)
		SELECT 
			d.NUM_DECOMPTE,
			(CASE WHEN d.CODE_OPERATEUR = 0 THEN @CODE_0 ELSE d.CODE_OPERATEUR END) AS CODE_OPERATEUR,
			d.DATE_DECOMPTE,
			d.MODE_PAIEMENT,
			d.CODE_CAISSE,
			d.MONTANT,
			d.DATE_HEURE_VERS,
			(CASE WHEN d.CODE_CLIENT = 0 THEN @CODE_0 ELSE d.CODE_CLIENT END) AS CODE_CLIENT,
			d.CODE_BANQUE,
			d.REFERENCE,
			d.REGLEMENT,
			d.DATE_VALIDATION, 
			@CODE_AGENCE AS CODE_AGCE 
		FROM 
			AGENCE_TAROUDANT.dbo.T_DECOMPTE d
			--INNER JOIN AGENCE_TAROUDANT.dbo.T_OPERATEUR o ON o.CODE_OPERATEUR = d.CODE_OPERATEUR
			--INNER JOIN AGENCE_TAROUDANT.dbo.T_CAISSE c ON c.CODE_CAISSE = d.CODE_CAISSE
		WHERE 
			d.DATE_DECOMPTE >= @DATE_OBJECTIF --AND c.CODE_AGCE=2

		-------- TABLE T_DT_DECOMPTE ----------
 
		INSERT INTO COMMERCIAL.dbo.T_DT_DECOMPTE
		(
			NUM_DECOMPTE,
			DATE_CHEQUE,
			DATE_ECHEANCE,
			GP_CLIENT,
			LE_TIRE,
			RIB,
			TYPE,
			RECEP1,
			RECEP2,
			ENCAISSEMENT,
			DATE_HEURE_ENCAISS,
			IMPAYE,
			DATE_HEURE_RETOUR,
			NUM_BORDERAU,
			OPERATEUR_SAISIE,
			OPERATEUR_RECEP1,
			OPERATEUR_RECEP2,
			MOTIF_ENVOI
		)
		SELECT 
			dtd.NUM_DECOMPTE,
			dtd.DATE_CHEQUE,
			dtd.DATE_ECHEANCE,
			dtd.GP_CLIENT,
			dtd.LE_TIRE,
			dtd.RIB,
			dtd.TYPE,
			dtd.RECEP1,
			dtd.RECEP2,
			dtd.ENCAISSEMENT,
			dtd.DATE_HEURE_ENCAISS,
			dtd.IMPAYE,
			dtd.DATE_HEURE_RETOUR,
			dtd.NUM_BORDERAU,
			dtd.OPERATEUR_SAISIE,
			dtd.OPERATEUR_RECEP1,
			dtd.OPERATEUR_RECEP2,
			dtd.MOTIF_ENVOI 
		FROM  
			AGENCE_TAROUDANT.dbo.T_DT_DECOMPTE dtd
			INNER JOIN AGENCE_TAROUDANT.dbo.T_DECOMPTE d ON d.NUM_DECOMPTE = dtd.NUM_DECOMPTE
		WHERE 
			d.DATE_DECOMPTE >= @DATE_OBJECTIF

		-------- TABLE T_OBJECTIF_AGENCE ----------
 
		INSERT INTO COMMERCIAL.dbo.T_OBJECTIF_AGENCE
		(
			DATE_OBJECTIF,
			CODE_PRODUIT,
			OBJECTIF_TRAD,
			OBJECTIF_GMS,
			OBJECTIF,
			CODE_AGCE
		)
		SELECT 
			o.DATE_OBJECTIF,
			o.CODE_PRODUIT,
			o.OBJECTIF_TRAD,
			o.OBJECTIF_GMS,
			o.OBJECTIF, 
			@CODE_AGENCE AS CODE_AGCE 
		FROM 
			AGENCE_TAROUDANT.dbo.T_OBJECTIF_AGENCE o
			INNER JOIN AGENCE_TAROUDANT.dbo.T_PRODUITS p ON p.CODE_PRODUIT = o.CODE_PRODUIT
		WHERE 
			o.DATE_OBJECTIF >= @DATE_OBJECTIF

		-------- TABLE T_OBJECTIF_CLIENTS ----------
 
		INSERT INTO COMMERCIAL.dbo.T_OBJECTIF_CLIENTS
		(
			DATE_OBJECTIF,
			CODE_CLIENT,
			CODE_PRODUIT,
			QTE_OBJECTIF,
			OBJECTIF_INVENDU,
			OBJECTIF_PERTE,
			CODE_AGCE
		)
		SELECT 
			o.DATE_OBJECTIF,
			(CASE WHEN o.CODE_CLIENT = 0 THEN @CODE_0 ELSE o.CODE_CLIENT END) AS CODE_CLIENT,
			o.CODE_PRODUIT,
			o.QTE_OBJECTIF,
			o.OBJECTIF_INVENDU,
			o.OBJECTIF_PERTE, 
			@CODE_AGENCE AS CODE_AGCE 
		FROM 
			AGENCE_TAROUDANT.dbo.T_OBJECTIF_CLIENTS o
			INNER JOIN AGENCE_TAROUDANT.dbo.T_PRODUITS p ON p.CODE_PRODUIT = o.CODE_PRODUIT
			INNER JOIN AGENCE_TAROUDANT.dbo.T_CLIENTS c ON c.CODE_CLIENT = o.CODE_CLIENT AND c.ACTIF = 1
		WHERE 
			o.DATE_OBJECTIF >= @DATE_OBJECTIF

		-------- TABLE T_OBJECTIF_RENDUS ----------
 
		INSERT INTO COMMERCIAL.dbo.T_OBJECTIF_RENDUS
		(
			DATE_OBJECTIF,
			CODE_ARTICLE,
			OBJ_RENDUS_US,
			OBJ_RENDUS_AG,
			OBJ_RENDUS_SP,
			CODE_AGCE
		)
		SELECT 
			o.DATE_OBJECTIF,
			o.CODE_ARTICLE,
			o.OBJ_RENDUS_US,
			o.OBJ_RENDUS_AG,
			o.OBJ_RENDUS_SP, 
			@CODE_AGENCE AS CODE_AGCE 
		FROM 
			AGENCE_TAROUDANT.dbo.T_OBJECTIF_RENDUS o
			INNER JOIN AGENCE_TAROUDANT.dbo.T_ARTICLES a ON a.CODE_ARTICLE = o.CODE_ARTICLE
		WHERE 
			o.DATE_OBJECTIF >= @DATE_OBJECTIF

		-------- TABLE T_OBJECTIF_SECTEURS ----------
 
		INSERT INTO COMMERCIAL.dbo.T_OBJECTIF_SECTEURS
		(
			DATE_OBJECTIF,
			CODE_SECTEUR,
			CODE_PRODUIT,
			QTE_OBJECTIF,
			OBJECTIF_INVENDU,
			OBJECTIF_PERTE
		)
		SELECT 
			o.DATE_OBJECTIF,
			(CASE WHEN o.CODE_SECTEUR = 0 THEN @CODE_0 ELSE o.CODE_SECTEUR END)  AS CODE_SECTEUR,
			o.CODE_PRODUIT,
			o.QTE_OBJECTIF,
			o.OBJECTIF_INVENDU,
			o.OBJECTIF_PERTE 
		FROM 
			AGENCE_TAROUDANT.dbo.T_OBJECTIF_SECTEURS o
			INNER JOIN AGENCE_TAROUDANT.dbo.T_PRODUITS p ON p.CODE_PRODUIT = o.CODE_PRODUIT
			INNER JOIN AGENCE_TAROUDANT.dbo.T_SECTEUR s ON s.CODE_SECTEUR = o.CODE_SECTEUR
		WHERE 
			o.DATE_OBJECTIF >= @DATE_OBJECTIF

		-------- TABLE T_OBJECTIF_VENTE ----------
 
		INSERT INTO COMMERCIAL.dbo.T_OBJECTIF_VENTE
		(
			DATE_OBJECTIF,
			CODE_SECTEUR,
			MONTANT_OBJECTIF
		)
		SELECT 
			o.DATE_OBJECTIF,
			(CASE WHEN o.CODE_SECTEUR = 0 THEN @CODE_0 ELSE o.CODE_SECTEUR END)  AS CODE_SECTEUR,
			o.MONTANT_OBJECTIF 
		FROM 
			AGENCE_TAROUDANT.dbo.T_OBJECTIF_VENTE o
			INNER JOIN AGENCE_TAROUDANT.dbo.T_SECTEUR s ON s.CODE_SECTEUR = o.CODE_SECTEUR
		WHERE 
			o.DATE_OBJECTIF >= @DATE_OBJECTIF

		-------- TABLE T_PREVISION ----------
 
		INSERT INTO COMMERCIAL.dbo.T_PREVISION
		(
			DATE_DEBUT,
			DATE_FIN,
			CODE_ARTICLE,
			QTE,
			CODE_AGCE
		)
		SELECT 
			p.DATE_DEBUT,
			p.DATE_FIN,
			p.CODE_ARTICLE,
			p.QTE, 
			@CODE_AGENCE AS CODE_AGCE 
		FROM 
			AGENCE_TAROUDANT.dbo.T_PREVISION p
			INNER JOIN AGENCE_TAROUDANT.dbo.T_ARTICLES a ON a.CODE_ARTICLE = p.CODE_ARTICLE
		WHERE 
			@DATE_OBJECTIF BETWEEN p.DATE_DEBUT AND p.DATE_FIN

		-------- TABLE T_PRIX ----------
 
		INSERT INTO COMMERCIAL.dbo.T_PRIX
		(
			DATE_DEBUT,
			CODE_AGCE,
			DATE_FIN,
			CODE_ARTICLE,
			PRIX
		)
		SELECT 
			p.DATE_DEBUT,
			p.CODE_AGCE,
			p.DATE_FIN,
			p.CODE_ARTICLE,
			p.PRIX 
		FROM 
			AGENCE_TAROUDANT.dbo.T_PRIX p
			INNER JOIN AGENCE_TAROUDANT.dbo.T_ARTICLES a ON a.CODE_ARTICLE = p.CODE_ARTICLE
			--INNER JOIN AGENCE_TAROUDANT.dbo.T_AGENCE ag ON ag.CODE_AGCE = p.CODE_AGCE
		--	'20180901' BETWEEN p.DATE_DEBUT AND p.DATE_FIN
		WHERE 
			p.CODE_AGCE = @CODE_AGENCE

		-------- TABLE T_RETOURS_USINE ----------
 
		INSERT INTO COMMERCIAL.dbo.T_RETOURS_USINE
		(
			ID_RETOUR,
			CODE_AGCE,
			NUM_CONVOYAGE,
			DATE_RETOUR,
			CATEGORIE,
			TRAITER_PAR,
			DATE_HEURE,
			COMPTAGE1_PAR,
			COMPTAGE2_PAR,
			COMPTE_ECART,
			VALID,
			REF_OPERATION,
			SCELLE1,
			SCELLE2,
			DATE_HEURE_SORTIE,
			SAISIE_AUTO,
			DATE_HEURE_ENTREE,
			COMMENTAIRE
		)
		SELECT 
			r.ID_RETOUR,
			r.CODE_AGCE,
			r.NUM_CONVOYAGE,
			r.DATE_RETOUR,
			r.CATEGORIE,
			r.TRAITER_PAR,
			r.DATE_HEURE,
			r.COMPTAGE1_PAR,
			r.COMPTAGE2_PAR,
			(CASE WHEN r.COMPTE_ECART = 0 THEN @CODE_0 ELSE r.COMPTE_ECART END)  AS COMPTE_ECART,
			r.VALID,
			r.REF_OPERATION,
			r.SCELLE1,
			r.SCELLE2,
			r.DATE_HEURE_SORTIE,
			r.SAISIE_AUTO,
			r.DATE_HEURE_ENTREE,
			r.COMMENTAIRE 
		FROM 
			AGENCE_TAROUDANT.dbo.T_RETOURS_USINE r
			--INNER JOIN AGENCE_TAROUDANT.dbo.T_AGENCE a ON a.CODE_AGCE = r.CODE_AGCE
		WHERE 
			CAST(r.DATE_HEURE AS DATE) >= @DATE_OBJECTIF

		-------- TABLE T_LIGNE_RETOUR_RENDUS ----------
 
		INSERT INTO COMMERCIAL.dbo.T_LIGNE_RETOUR_RENDUS
		(
			ID_RETOUR,
			CODE_ARTICLE,
			CATEGORIE,
			QTE_AGCE,
			COMPT1,
			COMPT2,
			ECART,
			PRIX
		)
		SELECT 
			l.ID_RETOUR,
			l.CODE_ARTICLE,
			l.CATEGORIE,
			l.QTE_AGCE,
			l.COMPT1,
			l.COMPT2,
			l.ECART,
			l.PRIX 
		FROM 
			AGENCE_TAROUDANT.dbo.T_LIGNE_RETOUR_RENDUS l
			INNER JOIN AGENCE_TAROUDANT.dbo.T_RETOURS_USINE r ON r.ID_RETOUR = l.ID_RETOUR
		WHERE 
			CAST(r.DATE_HEURE AS DATE) >= @DATE_OBJECTIF

		-------- TABLE T_LIGNE_RETOUR_CAISSERIE ----------
 
		INSERT INTO COMMERCIAL.dbo.T_LIGNE_RETOUR_CAISSERIE
		(
			ID_RETOUR,
			CODE_CP,
			QTE_AGCE,
			COMPT1,
			COMPT2,
			ECART
		)
		SELECT 
			l.ID_RETOUR,
			l.CODE_CP,
			l.QTE_AGCE,
			l.COMPT1,
			l.COMPT2,
			l.ECART 
		FROM 
			AGENCE_TAROUDANT.dbo.T_LIGNE_RETOUR_CAISSERIE l
			INNER JOIN AGENCE_TAROUDANT.dbo.T_RETOURS_USINE r ON r.ID_RETOUR = l.ID_RETOUR
		WHERE 
			CAST(r.DATE_HEURE AS DATE) >= @DATE_OBJECTIF

		-------- TABLE T_MAGASIN_COND ----------
 
		INSERT INTO COMMERCIAL.dbo.T_MAGASIN_COND
		(
			CODE_MAGASIN,
			CODE_CP,
			QTE_STOCK
		)
		SELECT 
			mc.CODE_MAGASIN,
			mc.CODE_CP,
			mc.QTE_STOCK 
		FROM 
			AGENCE_TAROUDANT.dbo.T_MAGASIN_COND mc
			INNER JOIN AGENCE_TAROUDANT.dbo.T_CAISSES_PALETTES cp ON cp.CODE_TYPE = mc.CODE_CP
			INNER JOIN AGENCE_TAROUDANT.dbo.T_MAGASINS m ON m.CODE_MAGASIN = mc.CODE_MAGASIN

		-------- TABLE T_LIVRAISON_PLANNING ----------
 
		INSERT INTO COMMERCIAL.dbo.T_LIVRAISON_PLANNING
		(
			CODE_CLIENT,
			CODE_AGCE,
			DERNIER_MAJ,
			LUNDI,
			MARDI,
			MERCREDI,
			JEUDI,
			VENDREDI,
			SAMEDI,
			DIMANCHE
		)
		SELECT 
			(CASE WHEN l.CODE_CLIENT = 0 THEN @CODE_0 ELSE l.CODE_CLIENT END) AS CODE_CLIENT,
			l.CODE_AGCE,
			l.DERNIER_MAJ,
			l.LUNDI,
			l.MARDI,
			l.MERCREDI,
			l.JEUDI,
			l.VENDREDI,
			l.SAMEDI,
			l.DIMANCHE 
		FROM 
			AGENCE_TAROUDANT.dbo.T_LIVRAISON_PLANNING l
			INNER JOIN AGENCE_TAROUDANT.dbo.T_CLIENTS c ON c.CODE_CLIENT = l.CODE_CLIENT AND c.ACTIF = 1
			--INNER JOIN AGENCE_TAROUDANT.dbo.T_AGENCE a ON a.CODE_AGCE = l.CODE_AGCE
		--WHERE l.CODE_AGCE=2

		-------- TABLE T_FACTURE ----------
 
		INSERT INTO COMMERCIAL.dbo.T_FACTURE
		(
			NUM_FACTURE,
			CODE_CLIENT,
			CODE_OPERATEUR,
			DATE_HEURE,
			MONTANT_FACTURE,
			MONTANT_PERTE,
			MONTANT_VERSE,
			VALID,
			LATITUDE_GPS,
			LONGITUDE_GPS,
			montant_remise,
			CODE_AGCE
		)
		SELECT 
			f.NUM_FACTURE,
			(CASE WHEN f.CODE_CLIENT = 0 THEN @CODE_0 ELSE f.CODE_CLIENT END) AS CODE_CLIENT,
			(CASE WHEN f.CODE_OPERATEUR = 0 THEN @CODE_0 ELSE f.CODE_OPERATEUR END) AS CODE_OPERATEUR,
			f.DATE_HEURE,
			f.MONTANT_FACTURE,
			f.MONTANT_PERTE,
			f.MONTANT_VERSE,
			f.VALID,
			f.LATITUDE_GPS,
			f.LONGITUDE_GPS,
			f.montant_remise, 
			@CODE_AGENCE AS CODE_AGCE 
		FROM 
			AGENCE_TAROUDANT.dbo.T_FACTURE f
			INNER JOIN AGENCE_TAROUDANT.dbo.T_CLIENTS c ON c.CODE_CLIENT = f.CODE_CLIENT
			--INNER JOIN AGENCE_TAROUDANT.dbo.T_OPERATEUR o ON o.CODE_OPERATEUR = f.CODE_OPERATEUR
		WHERE 
			CAST(f.DATE_HEURE AS DATE) >= @DATE_OBJECTIF

		-------- TABLE T_DT_FACTURE ----------
 
		INSERT INTO COMMERCIAL.dbo.T_DT_FACTURE
		(
			NUM_FACTURE,
			CODE_ARTICLE,
			PRIX,
			QTE_VENTE,
			QTE_PERTE,
			QTE_PROMO,
			QTE_REMISE,
			--TX_REMISE,
			TX_GRATUIT
		)
		SELECT 
			dtf.NUM_FACTURE,
			dtf.CODE_ARTICLE,
			dtf.PRIX,
			dtf.QTE_VENTE,
			dtf.QTE_PERTE,
			dtf.QTE_PROMO,
			dtf.QTE_REMISE,
			dtf.TX_GRATUIT 
		FROM 
			AGENCE_TAROUDANT.dbo.T_DT_FACTURE dtf
			INNER JOIN AGENCE_TAROUDANT.dbo.T_FACTURE f ON f.NUM_FACTURE = dtf.NUM_FACTURE 
			--INNER JOIN AGENCE_TAROUDANT.dbo.T_ARTICLES a ON a.CODE_ARTICLE = dtf.CODE_ARTICLE
		WHERE 
			CAST(f.DATE_HEURE AS DATE) >= @DATE_OBJECTIF

		-------- TABLE T_RECONAISSANCES ----------
 
		INSERT INTO COMMERCIAL.dbo.T_RECONAISSANCES
		(
			ID_RECONAISSANCE,
			CODE_CLIENT,
			CODE_OPERATEUR,
			DATE_RECONAISS,
			SOLDE_C_STD,
			SOLDE_P_AG,
			SOLDE_P_UHT,
			SOLDE_C_AG,
			SOLDE_C_PR,
			SOLDE_C_BLC,
			SOLDE_P_EURO,
			CS_1,
			CS_2,
			CODE_AGCE
		)
		SELECT 
			r.ID_RECONAISSANCE,
			(CASE WHEN r.CODE_CLIENT = 0 THEN @CODE_0 ELSE r.CODE_CLIENT END) AS CODE_CLIENT,
			(CASE WHEN r.CODE_OPERATEUR = 0 THEN @CODE_0 ELSE r.CODE_OPERATEUR END) AS CODE_OPERATEUR,
			r.DATE_RECONAISS,
			r.SOLDE_C_STD,
			r.SOLDE_P_AG,
			r.SOLDE_P_UHT,
			r.SOLDE_C_AG,
			r.SOLDE_C_PR,
			r.SOLDE_C_BLC,
			r.SOLDE_P_EURO,
			r.CS_1,
			r.CS_2, 
			@CODE_AGENCE AS CODE_AGCE 
		FROM 
			AGENCE_TAROUDANT.dbo.T_RECONAISSANCES r
			--INNER JOIN AGENCE_TAROUDANT.dbo.T_CLIENTS c ON c.CODE_CLIENT = r.CODE_CLIENT
			--INNER JOIN AGENCE_TAROUDANT.dbo.T_OPERATEUR o ON o.CODE_OPERATEUR = r.CODE_OPERATEUR
		--WHERE 
		--	r.DATE_RECONAISS >= @DATE_OBJECTIF

		-------- TABLE T_REGELEMENT_COND ----------
 
		INSERT INTO COMMERCIAL.dbo.T_REGELEMENT_COND
		(
			ID_REGLEMENT,
			CODE_OPERTAEUR,
			MONTANT_REGLER,
			REGLER_C_STD,
			REGLER_P_AG,
			REGLER_P_UHT,
			REGLER_C_AG,
			REGLER_C_PR,
			DATE_CREATION,
			DATE_VALIDATION,
			REGLER_C_BLC,
			REGLER_P_EURO,
			REGLER_CS1,
			REGLER_CS2,
			CODE_AGCE
		)
		SELECT 
			r.ID_REGLEMENT,
			(CASE WHEN r.CODE_OPERTAEUR = 0 THEN @CODE_0 ELSE r.CODE_OPERTAEUR END) AS CODE_OPERATEUR,
			r.MONTANT_REGLER,
			r.REGLER_C_STD,
			r.REGLER_P_AG,
			r.REGLER_P_UHT,
			r.REGLER_C_AG,
			r.REGLER_C_PR,
			r.DATE_CREATION,
			r.DATE_VALIDATION,
			r.REGLER_C_BLC,
			r.REGLER_P_EURO,
			r.REGLER_CS1,
			r.REGLER_CS2, 
			@CODE_AGENCE AS CODE_AGCE 
		FROM 
			AGENCE_TAROUDANT.dbo.T_REGELEMENT_COND r
			--INNER JOIN AGENCE_TAROUDANT.dbo.T_OPERATEUR o ON o.CODE_OPERATEUR = r.CODE_OPERTAEUR
		WHERE 
			CAST(r.DATE_CREATION AS DATE) >= @DATE_OBJECTIF

		-------- TABLE T_REMISE_CLIENT_TRAD ----------
 
		INSERT INTO COMMERCIAL.dbo.T_REMISE_CLIENT_TRAD
		(
			DATE_DEBUT,
			DATE_FIN,
			CODE_CLIENT,
			DATE_REMISE,
			MT_REMISE,
			MT_REPARTI,
			MT_CA,
			CODE_OPERATEUR,
			VALID,
			TX_DERIVES,
			CA_MOY,
			CA_MOY_LAIT,
			MT_REMISE_LAIT,
			TX_LAIT,
			DATE_SITUATION,
			STATUT,
			NUM_FACTURE,
			MONTANT_LIVRE,
			CODE_AGCE
		)
		SELECT 
			r.DATE_DEBUT,
			r.DATE_FIN,
			(CASE WHEN r.CODE_CLIENT = 0 THEN @CODE_0 ELSE r.CODE_CLIENT END) AS CODE_CLIENT,
			r.DATE_REMISE,
			r.MT_REMISE,
			r.MT_REPARTI,
			r.MT_CA,
			(CASE WHEN r.CODE_OPERATEUR = 0 THEN @CODE_0 ELSE r.CODE_OPERATEUR END) AS CODE_OPERATEUR,
			r.VALID,
			r.TX_DERIVES,
			r.CA_MOY,
			r.CA_MOY_LAIT,
			r.MT_REMISE_LAIT,
			r.TX_LAIT,
			r.DATE_SITUATION,
			r.STATUT,
			r.NUM_FACTURE,
			r.MONTANT_LIVRE,
			@CODE_AGENCE
		FROM 
			AGENCE_TAROUDANT.dbo.T_REMISE_CLIENT r
			INNER JOIN AGENCE_TAROUDANT.dbo.T_CLIENTS c ON c.CODE_CLIENT = r.CODE_CLIENT AND c.ACTIF = 1
			--INNER JOIN AGENCE_TAROUDANT.dbo.T_OPERATEUR o ON o.CODE_OPERATEUR = r.CODE_OPERATEUR
		WHERE 
			((@DATE_OBJECTIF BETWEEN r.DATE_DEBUT AND r.DATE_FIN) OR r.DATE_REMISE >= @DATE_OBJECTIF)

		-------- TABLE T_ECARTS_RENDUS ----------
 
		INSERT INTO COMMERCIAL.dbo.T_ECARTS_RENDUS
		(
			ID_ECART,
			DATE_SITUATION,
			DATE_HEURE_SAISIE,
			CODE_OPERATEUR,
			VALEUR_PRODUIT,
			CS_STD,
			CS_PRM,
			CS_AGR,
			PAL_STD,
			PAL_UHT,
			VALID,
			PAL_EURO,
			CS_BLC,
			CS_1,
			CS_2,
			CODE_AGCE
		)
		SELECT 
			e.ID_ECART,
			e.DATE_SITUATION,
			e.DATE_HEURE_SAISIE,
			(CASE WHEN e.CODE_OPERATEUR = 0 THEN @CODE_0 ELSE e.CODE_OPERATEUR END) AS CODE_OPERATEUR,
			e.VALEUR_PRODUIT,
			e.CS_STD,
			e.CS_PRM,
			e.CS_AGR,
			e.PAL_STD,
			e.PAL_UHT,
			e.VALID,
			e.PAL_EURO,
			e.CS_BLC,
			e.CS_1,
			e.CS_2, 
			@CODE_AGENCE AS CODE_AGCE 
		FROM 
			AGENCE_TAROUDANT.dbo.T_ECARTS_RENDUS e
			--INNER JOIN AGENCE_TAROUDANT.dbo.T_OPERATEUR o ON o.CODE_OPERATEUR = e.CODE_OPERATEUR
		WHERE 
			(e.DATE_SITUATION >= @DATE_OBJECTIF OR e.DATE_HEURE_SAISIE >= @DATE_OBJECTIF)

		-------- TABLE T_DT_REMISE_CLASSE ----------
 
		INSERT INTO COMMERCIAL.dbo.T_DT_REMISE_CLASSE
		(
			CODE_CLASSE,
			CODE_ARTICLE,
			TX_REMISE,
			CODE_AGCE
		)
		SELECT 
			dtr.CODE_CLASSE,
			dtr.CODE_ARTICLE,
			dtr.TX_REMISE, 
			@CODE_AGENCE CODE_AGCE 
		FROM 
			AGENCE_TAROUDANT.dbo.T_DT_REMISE_CLASSE dtr
			--INNER JOIN AGENCE_TAROUDANT.dbo.T_ARTICLES a ON a.CODE_ARTICLE = dtr.CODE_ARTICLE

		-------- TABLE T_PRELEVEMENT_SUSP_COND ----------
 
		INSERT INTO COMMERCIAL.dbo.T_PRELEVEMENT_SUSP_COND
		(
			ID_PRELEV,
			DATE_PRELEV,
			DATE_VALIDATION,
			CODE_AGCE
		)
		SELECT 
			p.ID_PRELEV,
			p.DATE_PRELEV,
			p.DATE_VALIDATION, 
			@CODE_AGENCE CODE_AGCE 
		FROM 
			AGENCE_TAROUDANT.dbo.T_PRELEVEMENT_SUSP_COND p
		WHERE 
			p.DATE_PRELEV >= @DATE_OBJECTIF OR p.DATE_VALIDATION >= @DATE_OBJECTIF

		-------- TABLE T_DT_PRELEVEMENT_COND ----------
 
		INSERT INTO COMMERCIAL.dbo.T_DT_PRELEVEMENT_COND
		(
			ID_PRELEVEMENT,
			CODE_OPERATEUR,
			SUSP_VENTE,
			SOLDE_STD,
			SOLDE_AGR,
			SOLDE_PRM,
			SOLDE_PAG,
			SOLDE_PUHT,
			DECON_STD,
			DECON_AGR,
			DECON_PRM,
			DECON_PAG,
			DECON_PUHT,
			PRIME_STD,
			PRIME_AGR,
			PRIME_PRM,
			PRIME_PAG,
			PRIME_PUHT,
			SOLDE_EURO,
			SOLDE_CBL,
			DECON_EURO,
			DECON_CBL,
			SOLDE_CS1,
			SOLDE_CS2,
			DECON_CS1,
			DECON_CS2
		)
		SELECT 
			dtp.ID_PRELEVEMENT,
			(CASE WHEN dtp.CODE_OPERATEUR = 0 THEN @CODE_0 ELSE dtp.CODE_OPERATEUR END) AS CODE_OPERATEUR,
			dtp.SUSP_VENTE,
			dtp.SOLDE_STD,
			dtp.SOLDE_AGR,
			dtp.SOLDE_PRM,
			dtp.SOLDE_PAG,
			dtp.SOLDE_PUHT,
			dtp.DECON_STD,
			dtp.DECON_AGR,
			dtp.DECON_PRM,
			dtp.DECON_PAG,
			dtp.DECON_PUHT,
			dtp.PRIME_STD,
			dtp.PRIME_AGR,
			dtp.PRIME_PRM,
			dtp.PRIME_PAG,
			dtp.PRIME_PUHT,
			dtp.SOLDE_EURO,
			dtp.SOLDE_CBL,
			dtp.DECON_EURO,
			dtp.DECON_CBL,
			dtp.SOLDE_CS1,
			dtp.SOLDE_CS2,
			dtp.DECON_CS1,
			dtp.DECON_CS2 
		FROM 
			AGENCE_TAROUDANT.dbo.T_DT_PRELEVEMENT_COND dtp
			INNER JOIN AGENCE_TAROUDANT.dbo.T_PRELEVEMENT_SUSP_COND p ON p.ID_PRELEV = dtp.ID_PRELEVEMENT	
			--INNER JOIN AGENCE_TAROUDANT.dbo.T_OPERATEUR o ON o.CODE_OPERATEUR = dtp.CODE_OPERATEUR
		WHERE 
			p.DATE_PRELEV >= @DATE_OBJECTIF OR p.DATE_VALIDATION >= @DATE_OBJECTIF
	
		-------- TABLE T_CIBLE_PROMOTION ----------
 
		INSERT INTO COMMERCIAL.dbo.T_CIBLE_PROMOTION 
		(
			ID_PROMO, 
			CODE_AGCE, 
			CODE_SECTEUR, 
			CODE_CLIENT
		)
		SELECT 
			cp.ID_PROMO,
			cp.CODE_AGCE,
			(CASE WHEN cp.CODE_SECTEUR = 0 THEN @CODE_0 ELSE cp.CODE_SECTEUR END) AS CODE_SECTEUR, 
			(CASE WHEN cp.CODE_CLIENT = 0 THEN @CODE_0 ELSE cp.CODE_CLIENT END) AS CODE_CLIENT
		FROM 
			AGENCE_TAROUDANT.dbo.T_CIBLE_PROMOTION cp
			--INNER JOIN AGENCE_TAROUDANT.dbo.T_AGENCE a ON a.CODE_AGCE = cp.CODE_AGCE
			INNER JOIN AGENCE_TAROUDANT.dbo.T_PROMOTIONS p ON p.ID_PROMO = cp.ID_PROMO
		WHERE 
			(p.DATE_HEURE >= @DATE_OBJECTIF OR (@DATE_OBJECTIF BETWEEN p.DATE_DEBUT AND p.DATE_FIN))
			--AND cp.ID_PROMO NOT IN (SELECT ID_PROMO FROM COMMERCIAL.dbo.T_PROMOTIONS)

		-------- TABLE T_MOY_VENTE_ARTICLE ----------
 
		INSERT INTO COMMERCIAL.dbo.T_MOY_VENTE_ARTICLE
		(
			DATE_VENTE,
			CODE_PRODUIT,
			CODE_SECTEUR,
			QTE_VENTE,
			QTE_PERTE,
			QTE_INVENDU
		)
		SELECT 
			m.DATE_VENTE,
			m.CODE_PRODUIT,
			(CASE WHEN m.CODE_SECTEUR = 0 THEN @CODE_0 ELSE m.CODE_SECTEUR END) AS CODE_SECTEUR, 
			m.QTE_VENTE,
			m.QTE_PERTE,
			m.QTE_INVENDU 
		FROM 
			AGENCE_TAROUDANT.dbo.T_MOY_VENTE_ARTICLE m
			INNER JOIN AGENCE_TAROUDANT.dbo.T_PRODUITS p ON p.CODE_PRODUIT = m.CODE_PRODUIT
			INNER JOIN AGENCE_TAROUDANT.dbo.T_SECTEUR s ON s.CODE_SECTEUR = m.CODE_SECTEUR
		WHERE 
			m.DATE_VENTE >= @DATE_OBJECTIF

		-------- TABLE T_MOY_VENTE_CLIENTS ----------
 
		INSERT INTO COMMERCIAL.dbo.T_MOY_VENTE_CLIENTS
		(
			DATE_VENTE,
			CODE_CLIENT,
			CODE_PRODUIT,
			QTE_VENTE,
			QTE_PERTE,
			CODE_AGCE
		)
		SELECT 
			m.DATE_VENTE,
			(CASE WHEN m.CODE_CLIENT = 0 THEN @CODE_0 ELSE m.CODE_CLIENT END) AS CODE_CLIENT,
			m.CODE_PRODUIT,
			m.QTE_VENTE,
			m.QTE_PERTE, 
			@CODE_AGENCE AS CODE_AGCE 
		FROM 
			AGENCE_TAROUDANT.dbo.T_MOY_VENTE_CLIENTS m
			INNER JOIN AGENCE_TAROUDANT.dbo.T_PRODUITS p ON p.CODE_PRODUIT = m.CODE_PRODUIT
			INNER JOIN AGENCE_TAROUDANT.dbo.T_CLIENTS c ON c.CODE_CLIENT = m.CODE_CLIENT AND c.ACTIF = 1
		WHERE 
			m.DATE_VENTE >= @DATE_OBJECTIF

		-------- TABLE T_HIST_TRAITEMENT_PDA ----------

		SET IDENTITY_INSERT COMMERCIAL.dbo.T_HIST_TRAITEMENT_PDA ON
		INSERT INTO COMMERCIAL.dbo.T_HIST_TRAITEMENT_PDA
		(
			ID_TRAITEMENT,
			CODE_SECTEUR,
			DATE_JOURNEE,
			DATE_HEURE_TRAITEMENT,
			VALID,
			MT_A_VERSER
		)
		SELECT 
			CAST(CONCAT(@CODE_AGENCE, h.ID_TRAITEMENT) AS INT) AS ID_TRAITEMENT,
			(CASE WHEN h.CODE_SECTEUR = 0 THEN @CODE_0 ELSE h.CODE_SECTEUR END) AS CODE_SECTEUR,
			h.DATE_JOURNEE,
			h.DATE_HEURE_TRAITEMENT,
			h.VALID,
			h.MT_A_VERSER 
		FROM 
			AGENCE_TAROUDANT.dbo.T_HIST_TRAITEMENT_PDA h
			INNER JOIN AGENCE_TAROUDANT.dbo.T_JOURNEE j ON j.DATE_JOURNEE = h.DATE_JOURNEE
			INNER JOIN AGENCE_TAROUDANT.dbo.T_SECTEUR s ON s.CODE_SECTEUR = h.CODE_SECTEUR
		WHERE 
			j.DATE_JOURNEE >= @DATE_OBJECTIF
		SET IDENTITY_INSERT COMMERCIAL.dbo.T_HIST_TRAITEMENT_PDA OFF

		-------- TABLE T_HISTORIQUE_OPERATIONS ----------

		SET IDENTITY_INSERT COMMERCIAL.dbo.T_HISTORIQUE_OPERATIONS ON
		INSERT INTO COMMERCIAL.dbo.T_HISTORIQUE_OPERATIONS
		(
			ID_EVENEMENT,
			DATE_HEURE,
			CODE_OPERATEUR,
			CAT,
			COMMENTAIRE,
			POSTE,
			SESSION
		)
		SELECT 
			CAST(CONCAT(@CODE_AGENCE, h.ID_EVENEMENT) AS INT) AS ID_EVENEMENT,
			h.DATE_HEURE,
			h.CODE_OPERATEUR,
			h.CAT,
			h.COMMENTAIRE,
			h.POSTE,
			h.SESSION 
		FROM 
			AGENCE_TAROUDANT.dbo.T_HISTORIQUE_OPERATIONS h
			INNER JOIN AGENCE_TAROUDANT.dbo.T_OPERATEUR o ON o.CODE_OPERATEUR = h.CODE_OPERATEUR
		WHERE 
			h.DATE_HEURE >= @DATE_OBJECTIF
		SET IDENTITY_INSERT COMMERCIAL.dbo.T_HISTORIQUE_OPERATIONS OFF

		-------- TABLE T_TOURNEES_SS ----------
 
		INSERT INTO COMMERCIAL.dbo.T_TOURNEES_SS
		(
			CODE_TOURNEE,
			CODE_SS,
			LUNDI,
			MARDI,
			MERCREDI,
			JEUDI,
			VENDREDI,
			SAMEDI,
			DIMANCHE
		)
		SELECT 
			(CASE WHEN ts.CODE_TOURNEE = 0 THEN @CODE_0 ELSE ts.CODE_TOURNEE END) AS CODE_TOURNEE,
			(CASE WHEN ts.CODE_SS = 0 THEN @CODE_0 ELSE ts.CODE_SS END) AS CODE_SS,
			ts.LUNDI,
			ts.MARDI,
			ts.MERCREDI,
			ts.JEUDI,
			ts.VENDREDI,
			ts.SAMEDI,
			ts.DIMANCHE 
		FROM 
			AGENCE_TAROUDANT.dbo.T_TOURNEES_SS ts
			INNER JOIN AGENCE_TAROUDANT.dbo.T_SOUS_SECTEUR ss ON ss.CODE_SOUS_SECTEUR = ts.CODE_SS

		-------- TABLE T_COURRIER_AGENCE ----------
 	
		INSERT INTO COMMERCIAL.dbo.T_COURRIER_AGENCE
		(
			ID_ENVOI,
			CAT,
			DATE_HEURE_SAISIE,
			DATE_HEURE_ENVOI,
			SAISIE_PAR,
			VALIDER_PAR,
			MATRICULE,
			DESTINATAIRE,
			VALID
		)
		SELECT 
			ca.ID_ENVOI,
			ca.CAT,
			ca.DATE_HEURE_SAISIE,
			ca.DATE_HEURE_ENVOI,
			(CASE WHEN ca.SAISIE_PAR = 0 THEN @CODE_0 ELSE ca.SAISIE_PAR END) AS SAISIE_PAR,
			ca.VALIDER_PAR,
			ca.MATRICULE,
			ca.DESTINATAIRE,
			ca.VALID 
		FROM 
			AGENCE_TAROUDANT.dbo.T_COURRIER_AGENCE ca
			INNER JOIN AGENCE_TAROUDANT.dbo.T_OPERATEUR o ON o.CODE_OPERATEUR = ca.SAISIE_PAR
		WHERE 
			(ca.DATE_HEURE_SAISIE >= @DATE_OBJECTIF OR ca.DATE_HEURE_ENVOI >= @DATE_OBJECTIF)

		-------- TABLE T_DT_COURRIER_AGENCE ----------
 
		INSERT INTO COMMERCIAL.dbo.T_DT_COURRIER_AGENCE
		(
			ID_ENVOI,
			TYPE_OP,
			SOUS_TYPE,
			ID_OPERATION,
			ID_AFFICHER
		)
		SELECT 
			dtca.ID_ENVOI,
			dtca.TYPE_OP,
			dtca.SOUS_TYPE,
			dtca.ID_OPERATION,
			dtca.ID_AFFICHER 
		FROM 
			AGENCE_TAROUDANT.dbo.T_DT_COURRIER_AGENCE dtca
			INNER JOIN AGENCE_TAROUDANT.dbo.T_COURRIER_AGENCE ca ON ca.ID_ENVOI = dtca.ID_ENVOI
		WHERE 
			ca.DATE_HEURE_SAISIE >= @DATE_OBJECTIF OR ca.DATE_HEURE_ENVOI >= @DATE_OBJECTIF

		-------- TABLE T_AFFECTATION ----------
 	
		INSERT INTO COMMERCIAL.dbo.T_AFFECTATION
		(
			code_secteur,
			code_vendeur,
			code_chauffeur,
			code_aide1,
			code_aide2,
			vehicule
		)
		SELECT 
			(CASE WHEN a.CODE_SECTEUR = 0 THEN @CODE_0 ELSE a.CODE_SECTEUR END) AS CODE_SECTEUR,
			(CASE WHEN a.code_vendeur = 0 THEN @CODE_0 ELSE a.code_vendeur END) AS code_vendeur,
			(CASE WHEN a.code_chauffeur = 0 THEN @CODE_0 ELSE a.code_chauffeur END) AS code_chauffeur,
			(CASE WHEN a.code_aide1 = 0 THEN @CODE_0 ELSE a.code_aide1 END) AS code_aide1,
			(CASE WHEN a.code_aide2 = 0 THEN @CODE_0 ELSE a.code_aide2 END) AS code_aide2,
			a.vehicule 
		FROM 
			AGENCE_TAROUDANT.dbo.T_AFFECTATION a 
			INNER JOIN AGENCE_TAROUDANT.dbo.T_SECTEUR s ON s.CODE_SECTEUR = a.code_secteur
		
		-------- TABLE T_MOUVEMENTS_CAISSE_CLIENTS ----------
 	
		INSERT INTO dbo.T_MOUVEMENTS_CAISSE_CLIENTS
		(
			CODE_CLIENT,
			DATE_OPERATION,
			CONSEIGNE,
			DECONSEIGNE,
			CODE_SECTEUR
		)
		SELECT 
			mv.CODE_CLIENT,
			mv.DATE_OPERATION,
			mv.CONSEIGNE,
			mv.DECONSEIGNE,
			(CASE WHEN mv.CODE_SECTEUR = 0 THEN @CODE_0 ELSE mv.CODE_SECTEUR END) AS CODE_SECTEUR 
		FROM 
			AGENCE_TAROUDANT.dbo.T_MOUVEMENTS_CAISSE_CLIENTS mv
		WHERE 
			mv.DATE_OPERATION >= @DATE_OBJECTIF
					
				-------- TABLE T_EVENEMENTS ----------
 		
		INSERT INTO COMMERCIAL.dbo.T_EVENEMENTS
		(
			DATE_HEURE,
			LIB_EVENEMENT,
			CODE_OPERATEUR
		)
		SELECT 
			e.DATE_HEURE,
			e.LIB_EVENEMENT,
			(CASE WHEN e.CODE_OPERATEUR = 0 THEN @CODE_0 ELSE e.CODE_OPERATEUR END) AS CODE_OPERATEUR 
		FROM 
			AGENCE_TAROUDANT.dbo.T_EVENEMENTS e
			INNER JOIN AGENCE_TAROUDANT.dbo.T_OPERATEUR o ON o.CODE_OPERATEUR = e.CODE_OPERATEUR
		WHERE 
			CAST(e.DATE_HEURE AS DATE) >= @DATE_OBJECTIF
		
		
		-------- TABLE T_COMMANDE_CLIENT ----------
 	
		INSERT INTO COMMERCIAL.dbo.T_COMMANDE_CLIENT
		(
			ID_COMMANDE,
			DATE_COMMANDE,
			CODE_CLIENT,
			DATE_HEURE_SAISIE,
			CODE_PREVENDEUR,
			STATUT,
			ETAT,
			NUM_FACTURE,
			CODE_SECTEUR,
			DATE_HEURE_LIVRAISON,
			CODE_LIVREUR
		)
		SELECT 
			c.ID_COMMANDE,
			c.DATE_COMMANDE,
			(CASE WHEN c.CODE_CLIENT = 0 THEN @CODE_0 ELSE c.CODE_CLIENT END) AS CODE_CLIENT,
			c.DATE_HEURE_SAISIE,
			c.CODE_PREVENDEUR,
			c.STATUT,
			c.ETAT,
			c.NUM_FACTURE,
			(CASE WHEN c.CODE_SECTEUR = 0 THEN @CODE_0 ELSE c.CODE_SECTEUR END) AS CODE_SECTEUR,
			c.DATE_HEURE_LIVRAISON,
			c.CODE_LIVREUR 
		FROM 
			AGENCE_TAROUDANT.dbo.T_COMMANDE_CLIENT c
			INNER JOIN AGENCE_TAROUDANT.dbo.T_CLIENTS cl ON cl.CODE_CLIENT = c.CODE_CLIENT AND cl.ACTIF = 1
			INNER JOIN AGENCE_TAROUDANT.dbo.T_OPERATEUR o ON o.CODE_OPERATEUR = c.CODE_PREVENDEUR
			INNER JOIN AGENCE_TAROUDANT.dbo.T_SECTEUR s ON s.CODE_SECTEUR = c.CODE_SECTEUR
		WHERE 
			c.DATE_COMMANDE >= @DATE_OBJECTIF
		
		-------- TABLE T_LIGNE_COMMANDE ----------
 	
		INSERT INTO COMMERCIAL.dbo.T_LIGNE_COMMANDE
		(
			ID_COMMANDE,
			CODE_ARTICLE,
			STOCK,
			QTE_COMMANDE,
			QTE_LIVREE,
			QTE_PERTE,
			QTE_PROMO,
			REMISE,
			PRIX,
			TX_GRATUIT
		)
		SELECT 
			lc.ID_COMMANDE,
			lc.CODE_ARTICLE,
			lc.STOCK,
			lc.QTE_COMMANDE,
			lc.QTE_LIVREE,
			lc.QTE_PERTE,
			lc.QTE_PROMO,
			lc.REMISE,
			lc.PRIX,
			lc.TX_GRATUIT 
		FROM 
			AGENCE_TAROUDANT.dbo.T_LIGNE_COMMANDE lc
			INNER JOIN AGENCE_TAROUDANT.dbo.T_COMMANDE_CLIENT c ON c.ID_COMMANDE = lc.ID_COMMANDE
			INNER JOIN AGENCE_TAROUDANT.dbo.T_ARTICLES a ON a.CODE_ARTICLE = lc.CODE_ARTICLE
		WHERE 
			c.DATE_COMMANDE >= @DATE_OBJECTIF
		

		COMMIT --VALIDATION TRANSACTION	
	END TRY
	BEGIN CATCH
		ROLLBACK --ANNULATION TRANSACTION
		DECLARE @ERR VARCHAR(MAX)
		SELECT @ERR=ERROR_MESSAGE()
		RAISERROR(@ERR,13,1) WITH SETERROR
		RETURN
	END CATCH
	
END