USE COMMERCIAL_T

DECLARE @SQL NVARCHAR(MAX),
		@CURSOR CURSOR 

SET @CURSOR = CURSOR FAST_FORWARD FOR
	SELECT DISTINCT SQL = 'ALTER TABLE [' + tc2.TABLE_NAME + '] DROP [' + rc1.CONSTRAINT_NAME + ']'
						FROM 
						INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS rc1
						LEFT JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc2 ON tc2.CONSTRAINT_NAME =rc1.CONSTRAINT_NAME

OPEN @CURSOR FETCH NEXT FROM @CURSOR INTO @SQL

WHILE (@@FETCH_STATUS = 0)
	BEGIN
		Exec sp_executesql @SQL
		FETCH NEXT FROM @CURSOR INTO @SQL
	END

CLOSE @CURSOR DEALLOCATE @CURSOR
GO

EXEC sp_MSforeachtable 'DROP TABLE ?'
GO