USE COMMERCIAL
GO

DECLARE @CODE_AGENCE INT = 2,
		@DATE_OBJECTIF NVARCHAR(10) = '20180901'

--- SYNCHRO BASE CENTRAL COMMERCIAL AVEC SIEGE

BEGIN
	SET NOCOUNT ON;
	BEGIN TRY
		BEGIN TRANSACTION
		-- TABLE T_AGENCE

		INSERT INTO COMMERCIAL.dbo.T_AGENCE
		(
			CODE_AGCE,
			NOM_AGENCE,
			COD_LONG,
			COD_STD,
			AFF_REPARTITION,
			AFF_SITUATION,
			COMMANDE_ACT,
			JOUR_COMMANDE,
			DERNIER_MAJ_STOCK,
			PREP_ACT,
			CODE_AGCE_COM,
			ID_LIEU,
			ACTIFS,
			CODETIERSNA,
			CODE_AGCE_ST,
			ID_LIEU_LIVRAISON,
			ID_IMPUTATION,
			CLE_REP_CA,
			ADRESSE,
			NUM_FAX,
			NUM_TEL
		)
		SELECT CODE_AGCE,
			NOM_AGENCE,
			COD_LONG,
			COD_STD,
			AFF_REPARTITION,
			AFF_SITUATION,
			COMMANDE_ACT,
			JOUR_COMMANDE,
			DERNIER_MAJ_STOCK,
			PREP_ACT,
			CODE_AGCE_COM,
			ID_LIEU,
			ACTIFS,
			CODETIERSNA,
			CODE_AGCE_ST,
			ID_LIEU_LIVRAISON,
			ID_IMPUTATION,
			CLE_REP_CA,
			ADRESSE,
			NUM_FAX,
			NUM_TEL 
		FROM 
			SIEGE.dbo.T_AGENCE

		-- TABLE T_CAISSES_PALETTES

		INSERT INTO COMMERCIAL.dbo.T_CAISSES_PALETTES 
		(
			CODE_TYPE, 
			NOM_TYPE, 
			ABREVIATION, 
			CATEGORIE, 
			PRIX_VENTE, 
			PRME_RECUP, RANG
		)
		SELECT 
			CODE_TYPE, 
			NOM_TYPE, 
			ABREVIATION, 
			CATEGORIE, 
			PRIX_VENTE, 
			PRME_RECUP, 
			RANG 
		FROM 
			SIEGE.dbo.T_CAISSES_PALETTES

		-- TABLE T_CLASSE_CLIENTS

		INSERT INTO COMMERCIAL.dbo.T_CLASSE_CLIENTS 
		(
			CODE_CLASSE,
			NOM_CLASSE
		)
		SELECT
			CODE_CLASSE, 
			NOM_CLASSE 
		FROM 
			SIEGE.dbo.T_CLASSE_CLIENTS

		-- TABLE T_CAT_CLIENTS

		INSERT INTO COMMERCIAL.dbo.T_CAT_CLIENTS 
		(
			CODE_CAT_CLIENT, 
			NOM_CATEGORIE
		)
		SELECT 
			c.CODE_CAT_CLIENT,
			c.NOM_CATEGORIE 
		FROM 
			SIEGE.dbo.T_CAT_CLIENTS c

		-- TABLE T_GROUP_CLIENT

		SET IDENTITY_INSERT COMMERCIAL.dbo.T_GROUP_CLIENT ON
		INSERT INTO COMMERCIAL.dbo.T_GROUP_CLIENT 
		(
			ID_GROUP, 
			NOM_GROUP, 
			TYPE_FACTURATION
		) 
		SELECT 
			ID_GROUP, 
			NOM_GROUP, 
			TYPE_FACTURATION 
		FROM 
			SIEGE.dbo.T_GROUP_CLIENT
		SET IDENTITY_INSERT COMMERCIAL.dbo.T_GROUP_CLIENT OFF

		-- TABLE T_GAMME

		INSERT INTO COMMERCIAL.dbo.T_GAMME 
		(
			CODE_GAMME,
			NOM_GAMME
		)
		SELECT 
			CODE_GAMME,
			NOM_GAMME 
		FROM 
			SIEGE.dbo.T_GAMME

		-- TABLE T_FAMILLE

		INSERT INTO COMMERCIAL.dbo.T_FAMILLE 
		(
			CODE_FAMILLE, 
			NOM_FAMILLE, 
			CODE_GAMME, 
			CONTRAT
		)
		SELECT 
			f.CODE_FAMILLE,
			f.NOM_FAMILLE,
			f.CODE_GAMME,
			f.CONTRAT 
		FROM 
			SIEGE.dbo.T_FAMILLE f
		--INNER JOIN SIEGE.dbo.T_GAMME g
		--	ON g.CODE_GAMME = f.CODE_GAMME

		-- TABLE T_PRODUITS

		INSERT INTO COMMERCIAL.dbo.T_PRODUITS 
		(
			CODE_PRODUIT, 
			CODE_FAMILLE, 
			NOM_PRODUIT, 
			ACTIF, 
			RANG_PRODUIT, 
			CAT_PRODUIT, 
			CYCLE
		)
		SELECT 
			p.CODE_PRODUIT,
			p.CODE_FAMILLE,
			p.NOM_PRODUIT,
			p.ACTIF,
			p.RANG_PRODUIT,
			p.CAT_PRODUIT,
			p.CYCLE 
		FROM 
			SIEGE.dbo.T_PRODUITS p
		--INNER JOIN SIEGE.dbo.T_FAMILLE f
		--	ON f.CODE_FAMILLE = p.CODE_FAMILLE
		--INNER JOIN SIEGE.dbo.T_GAMME g
		--	ON g.CODE_GAMME = f.CODE_GAMME

		-- TABLE T_GP_ARTICLES

		INSERT INTO COMMERCIAL.dbo.T_GP_ARTICLES 
		(
			CODE_GP_ARTICLE, 
			NOM_GP_ARTICLE
		)
		SELECT 
			CODE_GP_ARTICLE, 
			NOM_GP_ARTICLE 
		FROM 
			SIEGE.dbo.T_GP_ARTICLES

		-- TABLE T_AROMES

		INSERT INTO COMMERCIAL.dbo.T_AROMES 
		(
			CODE_AROME, 
			NOM
		)
		SELECT 
			CODE_AROME, 
			NOM 
		FROM 
			SIEGE.dbo.T_AROMES

		-- TABLE T_FONCTION

		INSERT INTO COMMERCIAL.dbo.T_FONCTION 
		(
			CODE_FONCTION, 
			NOM_FONCTION, 
			TAUX_COMISSION
		)
		SELECT 
			CODE_FONCTION, 
			NOM_FONCTION, 
			TAUX_COMISSION 
		FROM 
			SIEGE.dbo.T_FONCTION

		-- TABLE T_PARAMETRES_AGENCE

		INSERT INTO dbo.T_PARAMETRES_AGENCE
		(
			CODE_AGCE,
			MAG_STOCK,
			MAG_RENDUS,
			MAG_CAISSERIE,
			MAG_INVENDU,
			CAISSE_PRINCIPALE,
			CAISSE_DEPENSES
		)

		SELECT 
			CODE_AGCE,
			MAG_STOCK,
			MAG_RENDUS,
			MAG_CAISSERIE,
			MAG_INVENDU,
			CAISSE_PRINCIPALE,
			CAISSE_DEPENSES
		FROM 
			SIEGE.dbo.T_PARAMETRES_AGENCE

		-- TABLE T_MOTIF

		INSERT INTO COMMERCIAL.dbo.T_MOTIF 
		(
			CODE_MOTIF, 
			MOTIF, 
			MOTIF_TRANSFERT, 
			MOTIF_RETOUR_CAC, 
			MOTIF_REGULARISATION, 
			MOTIF_NON_VENTE
		)
		SELECT
			CODE_MOTIF, 
			MOTIF, 
			MOTIF_TRANSFERT, 
			MOTIF_RETOUR_CAC, 
			MOTIF_REGULARISATION, 
			MOTIF_NON_VENTE
		FROM 
			SIEGE.dbo.T_MOTIF

		-- TABLE T_MOTIF_RECLAMATION

		INSERT INTO COMMERCIAL.dbo.T_MOTIF_RECLAMATION 
		(
			ID_MOTIF, 
			LIBELLE, 
			CATEGORIE
		)
		SELECT
			ID_MOTIF, 
			LIBELLE, 
			CATEGORIE
		FROM 
			SIEGE.dbo.T_MOTIF_RECLAMATION

		-- TABLE T_MOTIFS_RETOUR

		INSERT INTO COMMERCIAL.dbo.T_MOTIFS_RETOUR 
		(
			CODE_MOTIF, 
			MOTIF
		)
		SELECT 
			CODE_MOTIF, 
			MOTIF
		FROM 
			SIEGE.dbo.T_MOTIFS_RETOUR

		-------- TABLE T_ARTICLES ----------
 
		INSERT INTO COMMERCIAL.dbo.T_ARTICLES 
		(
			CODE_ARTICLE, 
			CODE_BARRE, 
			RANG, 
			LIBELLE_COURT, 
			LIBELLE, 
			ABREVIATION, 
			GP_ARTICLE, 
			CODE_PRODUIT, 
			CODE_AROME, 
			TYPE_CAISSE, 
			TYPE_PALETTE, 
			TVA, 
			AFF_REPARTITION, 
			AFF_COMMANDE, 
			QTE_PACK, 
			QTE_PALETTE, 
			POIDS, 
			CONDITIONNEMENT, 
			ACTIF, 
			ACTIF_GLOBALE, 
			DISPO, 
			TX_COUVERTURE, 
			COMMANDE_MIN
		)
		SELECT 
			a.CODE_ARTICLE, 
			a.CODE_BARRE, 
			a.RANG, 
			a.LIBELLE_COURT, 
			a.LIBELLE, 
			a.ABREVIATION, 
			a.GP_ARTICLE, 
			a.CODE_PRODUIT,
			a.CODE_AROME, 
			NULL, --a.TYPE_CAISSE, 
			NULL, --a.TYPE_PALETTE, 
			a.TVA, 
			a.AFF_REPARTITION, 
			a.AFF_COMMANDE, 
			NULL, --a.QTE_PACK, 
			NULL, --a.QTE_PALETTE, 
			a.POIDS, 
			NULL, --a.CONDITIONNEMENT, 
			NULL, --a.ACTIF, 
			a.ACTIF_GLOBALE, 
			a.DISPO, 
			a.TX_COUVERTURE, 
			a.COMMANDE_MIN 
		FROM 
			SIEGE.dbo.T_ARTICLES a
		WHERE 
			a.CODE_ARTICLE NOT IN (SELECT CODE_ARTICLE FROM COMMERCIAL.dbo.T_ARTICLES)

		-------- TABLE T_ARTICLES_ENSEIGNE ----------

		SET IDENTITY_INSERT COMMERCIAL.dbo.T_ARTICLES_ENSEIGNE ON
		INSERT INTO COMMERCIAL.dbo.T_ARTICLES_ENSEIGNE
		(
			ID_ART_ENSEIGNE,
			ID_ENSEIGNE,
			CODE_ARTICLE,
			CODE_OPERATEUR,
			DATE_ADD
		)
		SELECT 
			ae.ID_ART_ENSEIGNE,
			ae.ID_ENSEIGNE,
			ae.CODE_ARTICLE,
			ae.CODE_OPERATEUR,
			ae.DATE_ADD
		FROM 
			SIEGE.dbo.T_ARTICLES_ENSEIGNE ae
			INNER JOIN SIEGE.dbo.T_ARTICLES a ON a.CODE_ARTICLE = ae.CODE_ARTICLE
		SET IDENTITY_INSERT COMMERCIAL.dbo.T_ARTICLES_ENSEIGNE OFF

		-------- TABLE T_PROMOTIONS ----------
 
		SET IDENTITY_INSERT COMMERCIAL.dbo.T_PROMOTIONS ON
		INSERT INTO COMMERCIAL.dbo.T_PROMOTIONS
		(
			ID_PROMO,
			DATE_HEURE,
			SAISIE_PAR,
			VALIDER_PAR,
			STATUT,
			DATE_DEBUT,
			DATE_FIN,
			DATE_HEURE_VALIDATION,
			CIBLE,
			COMMENTAIRE
		)
		SELECT 
			p.ID_PROMO,
			p.DATE_HEURE,
			p.SAISIE_PAR,
			p.VALIDER_PAR,
			p.STATUT,
			p.DATE_DEBUT,
			p.DATE_FIN,
			p.DATE_HEURE_VALIDATION,
			p.CIBLE,
			p.COMMENTAIRE 
		FROM 
			SIEGE.dbo.T_PROMOTIONS p
		--WHERE 
		--	(CAST(p.DATE_HEURE AS DATE) >= @DATE_OBJECTIF OR @DATE_OBJECTIF BETWEEN p.DATE_DEBUT AND p.DATE_FIN)
		--	AND p.ID_PROMO NOT IN (SELECT ID_PROMO FROM COMMERCIAL.dbo.T_PROMOTIONS)
		SET IDENTITY_INSERT COMMERCIAL.dbo.T_PROMOTIONS OFF

		-------- TABLE T_DT_PROMOTION ----------
 
		INSERT INTO dbo.T_DT_PROMOTION
		(
			ID_PROMO,
			CODE_ARTICLE,
			TYPE_PROMO,
			QTE_APPLI,
			QTE_GTATUIT,
			TX_GRATUIT,
			ART_DEST
		)
		SELECT
			dt.ID_PROMO,
			dt.CODE_ARTICLE,
			dt.TYPE_PROMO,
			dt.QTE_APPLI,
			dt.QTE_GTATUIT,
			dt.TX_GRATUIT,
			dt.ART_DEST 
		FROM 
			SIEGE.dbo.T_DT_PROMOTION dt
			INNER JOIN SIEGE.dbo.T_PROMOTIONS p ON p.ID_PROMO = dt.ID_PROMO
		--WHERE 
		--	(CAST(p.DATE_HEURE AS DATE) >= @DATE_OBJECTIF OR @DATE_OBJECTIF BETWEEN p.DATE_DEBUT AND p.DATE_FIN)
			--AND p.ID_PROMO NOT IN (SELECT ID_PROMO FROM COMMERCIAL.dbo.T_PROMOTIONS)

		-------- TABLE T_DT_PROMO_TRANCHE ----------
 
		INSERT INTO COMMERCIAL.dbo.T_DT_PROMO_TRANCHE
		(
			ID_PROMO,
			CODE_ARTICLE,
			TRANCHE,
			GRATUIT,
			TX_GRATUIT,
			CODE_AGCE
		)
		SELECT 
			dtp.ID_PROMO,
			dtp.CODE_ARTICLE,
			dtp.TRANCHE,
			dtp.GRATUIT,
			dtp.TX_GRATUIT, 
			@CODE_AGENCE AS CODE_AGCE 
		FROM 
			SIEGE.dbo.T_DT_PROMO_TRANCHE dtp
			INNER JOIN SIEGE.dbo.T_PROMOTIONS p ON p.ID_PROMO = dtp.ID_PROMO
			INNER JOIN SIEGE.dbo.T_ARTICLES a ON a.CODE_ARTICLE = dtp.CODE_ARTICLE
		--WHERE p.DATE_HEURE >= '20180916' OR '20180916' BETWEEN p.DATE_DEBUT AND p.DATE_FIN
		--WHERE 
		--	(p.DATE_HEURE >= @DATE_OBJECTIF OR (@DATE_OBJECTIF BETWEEN p.DATE_DEBUT AND p.DATE_FIN))

		COMMIT --VALIDATION TRANSACTION	
	END TRY
	BEGIN CATCH
		ROLLBACK --ANNULATION TRANSACTION
		DECLARE @ERR VARCHAR(MAX)
		SELECT @ERR=ERROR_MESSAGE()
		RAISERROR(@ERR,13,1) WITH SETERROR
		RETURN
	END CATCH
	
END