
IF NOT EXISTS (SELECT * FROM sys.sysobjects WHERE name='T_COMMANDE_CLIENT' AND xtype='U')
   CREATE TABLE [dbo].[T_COMMANDE_CLIENT](
	[ID_COMMANDE] [BIGINT] NOT NULL,
	[DATE_COMMANDE] [DATETIME] NULL,
	[CODE_CLIENT] [INT] NULL,
	[DATE_HEURE_SAISIE] [DATETIME] NULL,
	[CODE_PREVENDEUR] [INT] NULL,
	[STATUT] [TINYINT] NULL,
	[ETAT] [INT] NULL,
	[NUM_FACTURE] [BIGINT] NULL,
	[CODE_SECTEUR] [INT] NULL,
	[DATE_HEURE_LIVRAISON] [DATETIME] NULL,
	[CODE_LIVREUR] [INT] NULL
	)
GO

IF NOT EXISTS (SELECT * FROM sys.sysobjects WHERE name='T_LIGNE_COMMANDE' AND xtype='U')
	CREATE TABLE [dbo].[T_LIGNE_COMMANDE](
		[ID_COMMANDE] [bigint] NOT NULL,
		[CODE_ARTICLE] [int] NOT NULL,
		[STOCK] [int] NULL,
		[QTE_COMMANDE] [int] NULL,
		[QTE_LIVREE] [int] NULL,
		[QTE_PERTE] [int] NULL,
		[QTE_PROMO] [int] NULL,
		[REMISE] [int] NULL,
		[PRIX] [money] NULL,
		[TX_GRATUIT] [real] NULL
	)
GO

IF NOT EXISTS (SELECT * FROM sys.sysobjects WHERE name='T_MOUVEMENTS_CAISSE_CLIENTS' AND xtype='U')
	CREATE TABLE [dbo].[T_MOUVEMENTS_CAISSE_CLIENTS](
		[CODE_CLIENT] [int] NULL,
		[DATE_OPERATION] [datetime] NULL,
		[CONSEIGNE] [int] NULL,
		[DECONSEIGNE] [int] NULL,
		[CODE_SECTEUR] [int] NULL
	)
GO

IF NOT EXISTS (SELECT * FROM sys.sysobjects WHERE name='T_EVENEMENTS' AND xtype='U')
	CREATE TABLE [dbo].[T_EVENEMENTS](
		[ID_EVENEMENT] [int] IDENTITY(1,1) NOT NULL,
		[DATE_HEURE] [datetime] NULL,
		[LIB_EVENEMENT] [nvarchar](255) NULL,
		[CODE_OPERATEUR] [int] NULL
	)
GO
